-- agents.sql
-- Integrated reference for the agent/personhood schema.
--
-- This repository no longer treats governed embodiment as a separate
-- Supabase instance. The canonical additive migrations are:
--
-- 1. `supabase/migrations/20260330120000_trainer_core.sql`
--    Base `agents`, `agent_versions`, and trainer runtime tables.
--
-- 2. `supabase/migrations/20260410190000_agent_personhood_framework.sql`
--    Knowledge assets, manifests, mutations, and personhood-linked
--    read models already integrated into the shared project.
--
-- 3. `supabase/migrations/20260411110000_integrate_agent_identity_governance.sql`
--    Remaining identity/governance write models extracted from the
--    old standalone draft and added as an additive compatibility
--    layer on top of the shared schema.
--
-- Keep the migrations above as the source of truth. This file is now
-- a companion pointer so the project does not maintain a second,
-- divergent standalone schema definition.
