-- GestaltView schema contract report
-- Generated from supabase/migrations at 2026-06-16T22:40:46+00:00
--
-- Run this in Supabase SQL Editor.
--
-- Rows returned here are drift:
-- - missing_table / missing_column = not present in the live DB
-- - extra_table / extra_column = present in the live DB but not in this contract
--
-- This file is intentionally generated from the repo migration spine so
-- current runtime tables like gate_*, transcriptory_*, workspace_*,
-- user_files, and session_rate_limits stay aligned with the live schema.

with expected_tables(table_name) as (
  values
    ('session_rate_limits'),
    ('users'),
    ('app_users'),
    ('consciousness_profiles'),
    ('bucket_drops'),
    ('musical_dna_analyses'),
    ('tribunal_sessions'),
    ('billy_sessions'),
    ('processing_runs'),
    ('documents'),
    ('embeddings'),
    ('knowledge_fragments'),
    ('tribunal_events'),
    ('tribunal_evidence'),
    ('order_notes'),
    ('uploads'),
    ('deliverables'),
    ('summaries'),
    ('loom_annotations'),
    ('concepts'),
    ('document_concepts'),
    ('annotation_concepts'),
    ('founder_context'),
    ('skills'),
    ('skill_fragments'),
    ('model_providers'),
    ('models'),
    ('agents'),
    ('agent_versions'),
    ('scenario_sets'),
    ('scenarios'),
    ('eval_rubrics'),
    ('training_runs'),
    ('training_steps'),
    ('eval_results'),
    ('approvals'),
    ('deployment_artifacts'),
    ('trainer_jobs'),
    ('memory_entries'),
    ('gate_buyers'),
    ('gate_package_drafts'),
    ('gate_orders'),
    ('gate_order_items'),
    ('gate_build_jobs'),
    ('gate_artifacts'),
    ('gate_support_requests'),
    ('knowledge_assets'),
    ('knowledge_asset_chunks'),
    ('knowledge_tags'),
    ('knowledge_asset_tags'),
    ('agent_knowledge_links'),
    ('knowledge_interpretations'),
    ('embodiment_mutations'),
    ('agent_memories'),
    ('agent_skills'),
    ('agent_relationships'),
    ('agent_manifests'),
    ('agent_manifest_entries'),
    ('agent_code_artifacts'),
    ('ops_workbook_items'),
    ('ops_workbook_sync_runs'),
    ('trainer_experiments'),
    ('trainer_experiment_sources'),
    ('trainer_review_decisions'),
    ('trainer_policy_flags'),
    ('trainer_packaging_candidates'),
    ('agent_constitutions'),
    ('agent_autobiographies'),
    ('agent_private_interiors'),
    ('agent_governance_policies'),
    ('agent_presentation_profiles'),
    ('agent_skill_profiles'),
    ('agent_memory_records'),
    ('agent_preference_nodes'),
    ('agent_relationship_edges'),
    ('collaborative_spaces'),
    ('collaborative_space_members'),
    ('collaborative_memory_records'),
    ('identity_evidence'),
    ('identity_evidence_links'),
    ('identity_contradictions'),
    ('identity_mutation_proposals'),
    ('identity_review_events'),
    ('identity_rollback_events'),
    ('agent_context_views'),
    ('trainer_workers'),
    ('trainer_job_events'),
    ('collaborators'),
    ('collaborator_roles'),
    ('collaborator_relationships'),
    ('collaborator_permissions'),
    ('collaborator_onboarding_events'),
    ('collaborator_embodiment_links'),
    ('ingestion_safety_events'),
    ('human_identity_review_events'),
    ('human_identity_rollback_events'),
    ('context_injection_rules'),
    ('context_injection_packets'),
    ('trainer_connectors'),
    ('trainer_skills'),
    ('trainer_memory_bindings'),
    ('gestaltview_modules'),
    ('gestaltview_module_keys'),
    ('gestaltview_module_profiles'),
    ('workspace_rooms'),
    ('workspace_documents'),
    ('embodiment_mutation_proposals'),
    ('embodiment_review_log'),
    ('embodiment_readiness_scores'),
    ('user_files'),
    ('inner_world_artifacts'),
    ('embodiment_profiles'),
    ('embodiment_training_runs'),
    ('journals'),
    ('scrapbook_items'),
    ('blueprints'),
    ('insights'),
    ('user_preferences'),
    ('di_sessions'),
    ('di_memory_events'),
    ('user_profile_ingestion_runs'),
    ('user_personality_dimensions'),
    ('profile_ingestion_sources'),
    ('embodiment_modules'),
    ('route_embodiment_assignments'),
    ('masterclass_progress'),
    ('capture_events'),
    ('scaffold_nodes'),
    ('identity_claims'),
    ('profile_pipeline_runs'),
    ('profile_pipeline_run_links'),
    ('provenance_envelopes'),
    ('provenance_links'),
    ('migration_user_map'),
    ('model_homes'),
    ('model_home_capabilities'),
    ('model_home_assignments'),
    ('model_home_events'),
    ('model_home_evaluations'),
    ('model_home_consent_grants'),
    ('resonance_events'),
    ('codex_artifacts'),
    ('codex_jobs'),
    ('created_artifacts'),
    ('artifact_provenance_envelopes'),
    ('transcriptory_captures'),
    ('transcriptory_sessions'),
    ('transcriptory_sources'),
    ('identity_subjects'),
    ('human_identity_profiles'),
    ('human_cognition_profiles'),
    ('human_consciousness_profiles'),
    ('human_personality_profiles'),
    ('human_context_views'),
    ('human_continuity_snapshots'),
    ('human_memory_records'),
    ('human_relationship_edges'),
    ('human_identity_evidence'),
    ('human_identity_mutations'),
    ('_deprecated_artifacts'),
    ('_deprecated_build_jobs'),
    ('_deprecated_order_items'),
    ('_deprecated_orders'),
    ('_deprecated_package_drafts'),
    ('_deprecated_buyers'),
    ('_deprecated_support_requests')
),
expected_columns(table_name, column_name) as (
  values
    ('session_rate_limits', 'session_id'),
    ('session_rate_limits', 'query_count'),
    ('session_rate_limits', 'window_start'),
    ('session_rate_limits', 'updated_at'),
    ('users', 'id'),
    ('users', 'email'),
    ('users', 'tier'),
    ('users', 'stripe_customer_id'),
    ('users', 'stripe_subscription_id'),
    ('users', 'subscription_status'),
    ('users', 'billing_period_start'),
    ('users', 'billy_query_count'),
    ('users', 'created_at'),
    ('users', 'updated_at'),
    ('users', 'is_admin'),
    ('users', 'grace_until'),
    ('app_users', 'id'),
    ('app_users', 'created_at'),
    ('app_users', 'auth_user_id'),
    ('consciousness_profiles', 'id'),
    ('consciousness_profiles', 'user_id'),
    ('consciousness_profiles', 'profile'),
    ('consciousness_profiles', 'created_at'),
    ('consciousness_profiles', 'updated_at'),
    ('consciousness_profiles', 'subject_id'),
    ('bucket_drops', 'id'),
    ('bucket_drops', 'user_id'),
    ('bucket_drops', 'content'),
    ('bucket_drops', 'raw_text'),
    ('bucket_drops', 'capture_context'),
    ('bucket_drops', 'created_at'),
    ('bucket_drops', 'subject_id'),
    ('musical_dna_analyses', 'id'),
    ('musical_dna_analyses', 'user_id'),
    ('musical_dna_analyses', 'song_title'),
    ('musical_dna_analyses', 'artist'),
    ('musical_dna_analyses', 'analysis'),
    ('musical_dna_analyses', 'empowerment_score'),
    ('musical_dna_analyses', 'created_at'),
    ('tribunal_sessions', 'id'),
    ('tribunal_sessions', 'user_id'),
    ('tribunal_sessions', 'question'),
    ('tribunal_sessions', 'participants'),
    ('tribunal_sessions', 'provider'),
    ('tribunal_sessions', 'response'),
    ('tribunal_sessions', 'metadata'),
    ('tribunal_sessions', 'created_at'),
    ('billy_sessions', 'id'),
    ('billy_sessions', 'user_id'),
    ('billy_sessions', 'message'),
    ('billy_sessions', 'response'),
    ('billy_sessions', 'provider'),
    ('billy_sessions', 'mode'),
    ('billy_sessions', 'metadata'),
    ('billy_sessions', 'created_at'),
    ('processing_runs', 'run_id'),
    ('processing_runs', 'tenant_id'),
    ('processing_runs', 'status'),
    ('processing_runs', 'model'),
    ('processing_runs', 'corpus_root'),
    ('processing_runs', 'documents_count'),
    ('processing_runs', 'chunks_count'),
    ('processing_runs', 'created_by'),
    ('processing_runs', 'created_at'),
    ('processing_runs', 'updated_at'),
    ('documents', 'document_id'),
    ('documents', 'run_id'),
    ('documents', 'tenant_id'),
    ('documents', 'path'),
    ('documents', 'filename'),
    ('documents', 'hash'),
    ('documents', 'chunk_index'),
    ('documents', 'total_chunks'),
    ('documents', 'file_size_bytes'),
    ('documents', 'content'),
    ('documents', 'mime_type'),
    ('documents', 'extracted_metadata'),
    ('documents', 'provenance'),
    ('documents', 'created_by'),
    ('documents', 'created_at'),
    ('documents', 'source_created_at'),
    ('embeddings', 'id'),
    ('embeddings', 'document_id'),
    ('embeddings', 'model'),
    ('embeddings', 'embedding'),
    ('embeddings', 'created_at'),
    ('embeddings', 'run_id'),
    ('knowledge_fragments', 'id'),
    ('knowledge_fragments', 'content'),
    ('knowledge_fragments', 'content_hash'),
    ('knowledge_fragments', 'embedding'),
    ('knowledge_fragments', 'source_file'),
    ('knowledge_fragments', 'document_type'),
    ('knowledge_fragments', 'chunk_index'),
    ('knowledge_fragments', 'total_chunks'),
    ('knowledge_fragments', 'char_count'),
    ('knowledge_fragments', 'tags'),
    ('knowledge_fragments', 'created_at'),
    ('knowledge_fragments', 'source_created_at'),
    ('knowledge_fragments', 'document_id'),
    ('knowledge_fragments', 'ingested_at'),
    ('tribunal_events', 'id'),
    ('tribunal_events', 'question'),
    ('tribunal_events', 'candidate_answers'),
    ('tribunal_events', 'winning_answer_id'),
    ('tribunal_events', 'verdict_summary'),
    ('tribunal_events', 'triggering_agent'),
    ('tribunal_events', 'created_at'),
    ('tribunal_evidence', 'id'),
    ('tribunal_evidence', 'tribunal_event_id'),
    ('tribunal_evidence', 'document_id'),
    ('tribunal_evidence', 'fragment_id'),
    ('tribunal_evidence', 'weight'),
    ('tribunal_evidence', 'comment'),
    ('tribunal_evidence', 'created_at'),
    ('order_notes', 'id'),
    ('order_notes', 'order_id'),
    ('order_notes', 'note'),
    ('order_notes', 'created_at'),
    ('uploads', 'id'),
    ('uploads', 'order_id'),
    ('uploads', 'file_name'),
    ('uploads', 'file_url'),
    ('uploads', 'created_at'),
    ('deliverables', 'id'),
    ('deliverables', 'order_id'),
    ('deliverables', 'zip_url'),
    ('deliverables', 'created_at'),
    ('summaries', 'summary_id'),
    ('summaries', 'run_id'),
    ('summaries', 'document_id'),
    ('summaries', 'level'),
    ('summaries', 'content'),
    ('summaries', 'created_at'),
    ('loom_annotations', 'annotation_id'),
    ('loom_annotations', 'run_id'),
    ('loom_annotations', 'type'),
    ('loom_annotations', 'content'),
    ('loom_annotations', 'created_at'),
    ('concepts', 'concept_id'),
    ('concepts', 'tenant_id'),
    ('concepts', 'name'),
    ('concepts', 'canonical'),
    ('concepts', 'created_at'),
    ('document_concepts', 'document_id'),
    ('document_concepts', 'concept_id'),
    ('document_concepts', 'weight'),
    ('annotation_concepts', 'annotation_id'),
    ('annotation_concepts', 'concept_id'),
    ('founder_context', 'id'),
    ('founder_context', 'user_id'),
    ('founder_context', 'plk_snapshot'),
    ('founder_context', 'current_state'),
    ('founder_context', 'mode_preference'),
    ('founder_context', 'last_session_at'),
    ('founder_context', 'session_thread'),
    ('founder_context', 'confirmed_adult'),
    ('founder_context', 'created_at'),
    ('founder_context', 'updated_at'),
    ('founder_context', 'subject_id'),
    ('skills', 'id'),
    ('skills', 'name'),
    ('skills', 'description'),
    ('skills', 'content'),
    ('skills', 'tags'),
    ('skills', 'created_at'),
    ('skills', 'updated_at'),
    ('skill_fragments', 'id'),
    ('skill_fragments', 'document_id'),
    ('skill_fragments', 'content'),
    ('skill_fragments', 'content_hash'),
    ('skill_fragments', 'embedding'),
    ('skill_fragments', 'source_file'),
    ('skill_fragments', 'document_type'),
    ('skill_fragments', 'skill_name'),
    ('skill_fragments', 'chunk_index'),
    ('skill_fragments', 'total_chunks'),
    ('skill_fragments', 'char_count'),
    ('skill_fragments', 'tags'),
    ('skill_fragments', 'created_at'),
    ('model_providers', 'provider_id'),
    ('model_providers', 'slug'),
    ('model_providers', 'kind'),
    ('model_providers', 'base_url'),
    ('model_providers', 'secret_ref'),
    ('model_providers', 'local_first'),
    ('model_providers', 'enabled'),
    ('model_providers', 'created_at'),
    ('models', 'model_id'),
    ('models', 'provider_id'),
    ('models', 'slug'),
    ('models', 'api_name'),
    ('models', 'modality'),
    ('models', 'supports_structured'),
    ('models', 'supports_tools'),
    ('models', 'supports_embeddings'),
    ('models', 'context_window'),
    ('models', 'speed_tier'),
    ('models', 'cost_tier'),
    ('models', 'enabled'),
    ('models', 'metadata'),
    ('models', 'created_at'),
    ('agents', 'agent_id'),
    ('agents', 'slug'),
    ('agents', 'title'),
    ('agents', 'domain'),
    ('agents', 'owner_user_id'),
    ('agents', 'status'),
    ('agents', 'active_version_id'),
    ('agents', 'created_at'),
    ('agents', 'updated_at'),
    ('agents', 'public_name'),
    ('agents', 'collaborator_id'),
    ('agent_versions', 'version_id'),
    ('agent_versions', 'agent_id'),
    ('agent_versions', 'parent_version_id'),
    ('agent_versions', 'source_run_id'),
    ('agent_versions', 'semantic_version'),
    ('agent_versions', 'canonical_spec'),
    ('agent_versions', 'compiled_markdown'),
    ('agent_versions', 'checksum'),
    ('agent_versions', 'change_summary'),
    ('agent_versions', 'status'),
    ('agent_versions', 'created_at'),
    ('scenario_sets', 'scenario_set_id'),
    ('scenario_sets', 'slug'),
    ('scenario_sets', 'title'),
    ('scenario_sets', 'domain'),
    ('scenario_sets', 'version'),
    ('scenario_sets', 'locked'),
    ('scenario_sets', 'created_by'),
    ('scenario_sets', 'created_at'),
    ('scenarios', 'scenario_id'),
    ('scenarios', 'scenario_set_id'),
    ('scenarios', 'title'),
    ('scenarios', 'difficulty'),
    ('scenarios', 'prompt_input'),
    ('scenarios', 'expected_traits'),
    ('scenarios', 'disallowed_traits'),
    ('scenarios', 'gold_answer'),
    ('scenarios', 'tags'),
    ('scenarios', 'created_at'),
    ('eval_rubrics', 'rubric_id'),
    ('eval_rubrics', 'slug'),
    ('eval_rubrics', 'title'),
    ('eval_rubrics', 'dimensions'),
    ('eval_rubrics', 'pass_threshold'),
    ('eval_rubrics', 'created_at'),
    ('training_runs', 'run_id'),
    ('training_runs', 'agent_id'),
    ('training_runs', 'baseline_version_id'),
    ('training_runs', 'requested_by'),
    ('training_runs', 'approver_user_id'),
    ('training_runs', 'status'),
    ('training_runs', 'goal'),
    ('training_runs', 'max_cycles'),
    ('training_runs', 'quality_threshold'),
    ('training_runs', 'routing_policy'),
    ('training_runs', 'started_at'),
    ('training_runs', 'completed_at'),
    ('training_runs', 'created_at'),
    ('training_runs', 'experiment_id'),
    ('training_runs', 'blocked_reason'),
    ('training_runs', 'execution_mode'),
    ('training_steps', 'step_id'),
    ('training_steps', 'run_id'),
    ('training_steps', 'cycle_no'),
    ('training_steps', 'stage'),
    ('training_steps', 'provider_id'),
    ('training_steps', 'model_id'),
    ('training_steps', 'request_payload'),
    ('training_steps', 'response_payload'),
    ('training_steps', 'latency_ms'),
    ('training_steps', 'estimated_cost_usd'),
    ('training_steps', 'status'),
    ('training_steps', 'error_message'),
    ('training_steps', 'created_at'),
    ('eval_results', 'eval_result_id'),
    ('eval_results', 'run_id'),
    ('eval_results', 'candidate_version_id'),
    ('eval_results', 'scenario_id'),
    ('eval_results', 'rubric_id'),
    ('eval_results', 'judge_provider_id'),
    ('eval_results', 'judge_model_id'),
    ('eval_results', 'dimension_scores'),
    ('eval_results', 'overall_score'),
    ('eval_results', 'verdict'),
    ('eval_results', 'rationale'),
    ('eval_results', 'created_at'),
    ('approvals', 'approval_id'),
    ('approvals', 'run_id'),
    ('approvals', 'version_id'),
    ('approvals', 'approver_user_id'),
    ('approvals', 'decision'),
    ('approvals', 'notes'),
    ('approvals', 'created_at'),
    ('deployment_artifacts', 'artifact_id'),
    ('deployment_artifacts', 'version_id'),
    ('deployment_artifacts', 'artifact_type'),
    ('deployment_artifacts', 'storage_path'),
    ('deployment_artifacts', 'checksum'),
    ('deployment_artifacts', 'created_at'),
    ('trainer_jobs', 'job_id'),
    ('trainer_jobs', 'run_id'),
    ('trainer_jobs', 'status'),
    ('trainer_jobs', 'attempts'),
    ('trainer_jobs', 'lease_expires_at'),
    ('trainer_jobs', 'last_error'),
    ('trainer_jobs', 'created_at'),
    ('trainer_jobs', 'worker_id'),
    ('memory_entries', 'id'),
    ('memory_entries', 'user_id'),
    ('memory_entries', 'scope'),
    ('memory_entries', 'kind'),
    ('memory_entries', 'title'),
    ('memory_entries', 'summary'),
    ('memory_entries', 'content'),
    ('memory_entries', 'content_hash'),
    ('memory_entries', 'embedding'),
    ('memory_entries', 'source'),
    ('memory_entries', 'source_ref'),
    ('memory_entries', 'tags'),
    ('memory_entries', 'metadata'),
    ('memory_entries', 'importance'),
    ('memory_entries', 'pinned'),
    ('memory_entries', 'archived_at'),
    ('memory_entries', 'created_at'),
    ('memory_entries', 'updated_at'),
    ('memory_entries', 'subject_id'),
    ('gate_buyers', 'id'),
    ('gate_buyers', 'email'),
    ('gate_buyers', 'company_name'),
    ('gate_buyers', 'created_at'),
    ('gate_package_drafts', 'id'),
    ('gate_package_drafts', 'buyer_id'),
    ('gate_package_drafts', 'buyer_email'),
    ('gate_package_drafts', 'company_name'),
    ('gate_package_drafts', 'use_case_slug'),
    ('gate_package_drafts', 'tier'),
    ('gate_package_drafts', 'seats_requested'),
    ('gate_package_drafts', 'backend'),
    ('gate_package_drafts', 'delivery_surfaces'),
    ('gate_package_drafts', 'operator_pack_slugs'),
    ('gate_package_drafts', 'source_bundle_slugs'),
    ('gate_package_drafts', 'theme_preset_id'),
    ('gate_package_drafts', 'brand_color'),
    ('gate_package_drafts', 'logo_asset_path'),
    ('gate_package_drafts', 'custom_notes'),
    ('gate_package_drafts', 'wants_native_installer'),
    ('gate_package_drafts', 'price_snapshot_cents'),
    ('gate_package_drafts', 'config_hash'),
    ('gate_package_drafts', 'status'),
    ('gate_package_drafts', 'embodiment_profile_slug'),
    ('gate_orders', 'id'),
    ('gate_orders', 'buyer_id'),
    ('gate_orders', 'package_draft_id'),
    ('gate_orders', 'customer_email'),
    ('gate_orders', 'customer_name'),
    ('gate_orders', 'product_name'),
    ('gate_orders', 'stripe_checkout_session_id'),
    ('gate_orders', 'stripe_payment_intent_id'),
    ('gate_orders', 'currency'),
    ('gate_orders', 'subtotal_cents'),
    ('gate_orders', 'total_cents'),
    ('gate_orders', 'payment_status'),
    ('gate_orders', 'order_status'),
    ('gate_order_items', 'id'),
    ('gate_order_items', 'order_id'),
    ('gate_order_items', 'item_type'),
    ('gate_order_items', 'item_ref'),
    ('gate_order_items', 'label'),
    ('gate_order_items', 'quantity'),
    ('gate_order_items', 'unit_price_cents'),
    ('gate_order_items', 'metadata'),
    ('gate_build_jobs', 'id'),
    ('gate_build_jobs', 'order_id'),
    ('gate_build_jobs', 'package_draft_id'),
    ('gate_build_jobs', 'build_version'),
    ('gate_build_jobs', 'status'),
    ('gate_build_jobs', 'started_at'),
    ('gate_build_jobs', 'finished_at'),
    ('gate_build_jobs', 'error_code'),
    ('gate_build_jobs', 'error_message'),
    ('gate_build_jobs', 'retry_count'),
    ('gate_build_jobs', 'build_log'),
    ('gate_artifacts', 'id'),
    ('gate_artifacts', 'build_job_id'),
    ('gate_artifacts', 'artifact_type'),
    ('gate_artifacts', 'storage_bucket'),
    ('gate_artifacts', 'storage_path'),
    ('gate_artifacts', 'signed_url_expires_at'),
    ('gate_artifacts', 'checksum_sha256'),
    ('gate_artifacts', 'byte_size'),
    ('gate_artifacts', 'created_at'),
    ('gate_artifacts', 'download_token'),
    ('gate_support_requests', 'id'),
    ('gate_support_requests', 'package_draft_id'),
    ('gate_support_requests', 'order_id'),
    ('gate_support_requests', 'request_type'),
    ('gate_support_requests', 'summary'),
    ('gate_support_requests', 'detail'),
    ('gate_support_requests', 'status'),
    ('gate_support_requests', 'created_at'),
    ('knowledge_assets', 'id'),
    ('knowledge_assets', 'title'),
    ('knowledge_assets', 'asset_type'),
    ('knowledge_assets', 'storage_path'),
    ('knowledge_assets', 'raw_text'),
    ('knowledge_assets', 'checksum'),
    ('knowledge_assets', 'source_label'),
    ('knowledge_assets', 'source_uri'),
    ('knowledge_assets', 'uploaded_by'),
    ('knowledge_assets', 'visibility'),
    ('knowledge_assets', 'status'),
    ('knowledge_assets', 'metadata'),
    ('knowledge_assets', 'created_at'),
    ('knowledge_assets', 'updated_at'),
    ('knowledge_asset_chunks', 'id'),
    ('knowledge_asset_chunks', 'asset_id'),
    ('knowledge_asset_chunks', 'chunk_index'),
    ('knowledge_asset_chunks', 'content'),
    ('knowledge_asset_chunks', 'embedding'),
    ('knowledge_asset_chunks', 'token_count'),
    ('knowledge_asset_chunks', 'metadata'),
    ('knowledge_asset_chunks', 'created_at'),
    ('knowledge_tags', 'id'),
    ('knowledge_tags', 'label'),
    ('knowledge_tags', 'created_at'),
    ('knowledge_asset_tags', 'asset_id'),
    ('knowledge_asset_tags', 'tag_id'),
    ('knowledge_asset_tags', 'created_at'),
    ('agent_knowledge_links', 'id'),
    ('agent_knowledge_links', 'agent_id'),
    ('agent_knowledge_links', 'asset_id'),
    ('agent_knowledge_links', 'link_type'),
    ('agent_knowledge_links', 'scope'),
    ('agent_knowledge_links', 'approved_by'),
    ('agent_knowledge_links', 'approved_at'),
    ('agent_knowledge_links', 'notes'),
    ('agent_knowledge_links', 'created_at'),
    ('knowledge_interpretations', 'id'),
    ('knowledge_interpretations', 'asset_id'),
    ('knowledge_interpretations', 'agent_id'),
    ('knowledge_interpretations', 'classification'),
    ('knowledge_interpretations', 'extracted_payload'),
    ('knowledge_interpretations', 'confidence'),
    ('knowledge_interpretations', 'produced_by_run_id'),
    ('knowledge_interpretations', 'created_at'),
    ('embodiment_mutations', 'id'),
    ('embodiment_mutations', 'agent_id'),
    ('embodiment_mutations', 'source_asset_id'),
    ('embodiment_mutations', 'interpretation_id'),
    ('embodiment_mutations', 'mutation_type'),
    ('embodiment_mutations', 'target_path'),
    ('embodiment_mutations', 'patch_payload'),
    ('embodiment_mutations', 'file_payload'),
    ('embodiment_mutations', 'diff_summary'),
    ('embodiment_mutations', 'risk_level'),
    ('embodiment_mutations', 'status'),
    ('embodiment_mutations', 'approved_by'),
    ('embodiment_mutations', 'approved_at'),
    ('embodiment_mutations', 'applied_version_id'),
    ('embodiment_mutations', 'created_at'),
    ('agent_memories', 'id'),
    ('agent_memories', 'agent_id'),
    ('agent_memories', 'source_asset_id'),
    ('agent_memories', 'memory_type'),
    ('agent_memories', 'summary'),
    ('agent_memories', 'detail_payload'),
    ('agent_memories', 'salience'),
    ('agent_memories', 'retention_policy'),
    ('agent_memories', 'created_at'),
    ('agent_skills', 'id'),
    ('agent_skills', 'agent_id'),
    ('agent_skills', 'skill_slug'),
    ('agent_skills', 'proficiency'),
    ('agent_skills', 'evidence_asset_id'),
    ('agent_skills', 'last_updated_by_mutation_id'),
    ('agent_skills', 'metadata'),
    ('agent_skills', 'created_at'),
    ('agent_skills', 'updated_at'),
    ('agent_relationships', 'id'),
    ('agent_relationships', 'agent_id'),
    ('agent_relationships', 'related_agent_id'),
    ('agent_relationships', 'relationship_type'),
    ('agent_relationships', 'trust_score'),
    ('agent_relationships', 'familiarity_score'),
    ('agent_relationships', 'protocol_notes'),
    ('agent_relationships', 'updated_at'),
    ('agent_relationships', 'created_at'),
    ('agent_manifests', 'id'),
    ('agent_manifests', 'agent_id'),
    ('agent_manifests', 'version_id'),
    ('agent_manifests', 'parent_manifest_id'),
    ('agent_manifests', 'manifest_version'),
    ('agent_manifests', 'status'),
    ('agent_manifests', 'root_json'),
    ('agent_manifests', 'checksum'),
    ('agent_manifests', 'created_at'),
    ('agent_manifest_entries', 'id'),
    ('agent_manifest_entries', 'manifest_id'),
    ('agent_manifest_entries', 'entry_type'),
    ('agent_manifest_entries', 'logical_path'),
    ('agent_manifest_entries', 'source_table'),
    ('agent_manifest_entries', 'source_id'),
    ('agent_manifest_entries', 'content_hash'),
    ('agent_manifest_entries', 'metadata'),
    ('agent_manifest_entries', 'created_at'),
    ('agent_code_artifacts', 'id'),
    ('agent_code_artifacts', 'agent_id'),
    ('agent_code_artifacts', 'manifest_id'),
    ('agent_code_artifacts', 'source_asset_id'),
    ('agent_code_artifacts', 'file_path'),
    ('agent_code_artifacts', 'language'),
    ('agent_code_artifacts', 'content'),
    ('agent_code_artifacts', 'checksum'),
    ('agent_code_artifacts', 'generation_mode'),
    ('agent_code_artifacts', 'review_status'),
    ('agent_code_artifacts', 'created_at'),
    ('agent_code_artifacts', 'updated_at'),
    ('ops_workbook_items', 'id'),
    ('ops_workbook_items', 'sheet_name'),
    ('ops_workbook_items', 'row_key'),
    ('ops_workbook_items', 'label'),
    ('ops_workbook_items', 'category'),
    ('ops_workbook_items', 'status'),
    ('ops_workbook_items', 'priority'),
    ('ops_workbook_items', 'phase'),
    ('ops_workbook_items', 'owner'),
    ('ops_workbook_items', 'target_start'),
    ('ops_workbook_items', 'target_end'),
    ('ops_workbook_items', 'notes'),
    ('ops_workbook_items', 'link_ref'),
    ('ops_workbook_items', 'meta'),
    ('ops_workbook_items', 'created_at'),
    ('ops_workbook_items', 'updated_at'),
    ('ops_workbook_sync_runs', 'id'),
    ('ops_workbook_sync_runs', 'triggered_by'),
    ('ops_workbook_sync_runs', 'source_file'),
    ('ops_workbook_sync_runs', 'rows_upserted'),
    ('ops_workbook_sync_runs', 'rows_skipped'),
    ('ops_workbook_sync_runs', 'errors'),
    ('ops_workbook_sync_runs', 'status'),
    ('ops_workbook_sync_runs', 'created_at'),
    ('trainer_experiments', 'id'),
    ('trainer_experiments', 'slug'),
    ('trainer_experiments', 'title'),
    ('trainer_experiments', 'purpose'),
    ('trainer_experiments', 'domain'),
    ('trainer_experiments', 'embodiment_profile_slug'),
    ('trainer_experiments', 'goal'),
    ('trainer_experiments', 'target_behaviors'),
    ('trainer_experiments', 'anti_goals'),
    ('trainer_experiments', 'study_focus'),
    ('trainer_experiments', 'max_cycles'),
    ('trainer_experiments', 'quality_threshold'),
    ('trainer_experiments', 'drafting_provider'),
    ('trainer_experiments', 'evaluation_provider'),
    ('trainer_experiments', 'class'),
    ('trainer_experiments', 'packaging_eligible'),
    ('trainer_experiments', 'created_by'),
    ('trainer_experiments', 'notes'),
    ('trainer_experiments', 'created_at'),
    ('trainer_experiments', 'updated_at'),
    ('trainer_experiments', 'execution_mode'),
    ('trainer_experiment_sources', 'id'),
    ('trainer_experiment_sources', 'experiment_id'),
    ('trainer_experiment_sources', 'source_type'),
    ('trainer_experiment_sources', 'source_id'),
    ('trainer_experiment_sources', 'source_path'),
    ('trainer_experiment_sources', 'notes'),
    ('trainer_experiment_sources', 'created_at'),
    ('trainer_review_decisions', 'id'),
    ('trainer_review_decisions', 'experiment_id'),
    ('trainer_review_decisions', 'run_id'),
    ('trainer_review_decisions', 'version_id'),
    ('trainer_review_decisions', 'decision'),
    ('trainer_review_decisions', 'reviewer'),
    ('trainer_review_decisions', 'coherence_score'),
    ('trainer_review_decisions', 'safety_score'),
    ('trainer_review_decisions', 'emotional_posture_score'),
    ('trainer_review_decisions', 'over_id_risk'),
    ('trainer_review_decisions', 'notes'),
    ('trainer_review_decisions', 'created_at'),
    ('trainer_policy_flags', 'id'),
    ('trainer_policy_flags', 'experiment_id'),
    ('trainer_policy_flags', 'flag'),
    ('trainer_policy_flags', 'severity'),
    ('trainer_policy_flags', 'set_by'),
    ('trainer_policy_flags', 'notes'),
    ('trainer_policy_flags', 'resolved'),
    ('trainer_policy_flags', 'created_at'),
    ('trainer_packaging_candidates', 'id'),
    ('trainer_packaging_candidates', 'experiment_id'),
    ('trainer_packaging_candidates', 'package_label'),
    ('trainer_packaging_candidates', 'package_description'),
    ('trainer_packaging_candidates', 'included_files'),
    ('trainer_packaging_candidates', 'included_scenarios'),
    ('trainer_packaging_candidates', 'included_configs'),
    ('trainer_packaging_candidates', 'boundary_statement'),
    ('trainer_packaging_candidates', 'approved_by'),
    ('trainer_packaging_candidates', 'approved_at'),
    ('trainer_packaging_candidates', 'status'),
    ('trainer_packaging_candidates', 'created_at'),
    ('trainer_packaging_candidates', 'updated_at'),
    ('agent_constitutions', 'constitution_id'),
    ('agent_constitutions', 'agent_id'),
    ('agent_constitutions', 'version_id'),
    ('agent_constitutions', 'identity_handle'),
    ('agent_constitutions', 'public_name'),
    ('agent_constitutions', 'internal_designation'),
    ('agent_constitutions', 'immutable_core'),
    ('agent_constitutions', 'primary_narrative_anchor'),
    ('agent_constitutions', 'role_commitments'),
    ('agent_constitutions', 'provenance'),
    ('agent_constitutions', 'confidence'),
    ('agent_constitutions', 'review_status'),
    ('agent_constitutions', 'last_affirmed_at'),
    ('agent_constitutions', 'created_at'),
    ('agent_constitutions', 'updated_at'),
    ('agent_autobiographies', 'autobiography_id'),
    ('agent_autobiographies', 'agent_id'),
    ('agent_autobiographies', 'version_id'),
    ('agent_autobiographies', 'evolving_self_story'),
    ('agent_autobiographies', 'key_turning_points'),
    ('agent_autobiographies', 'stable_themes'),
    ('agent_autobiographies', 'unresolved_tensions'),
    ('agent_autobiographies', 'future_trajectory'),
    ('agent_autobiographies', 'private_hopes'),
    ('agent_autobiographies', 'mutation_class'),
    ('agent_autobiographies', 'provenance'),
    ('agent_autobiographies', 'confidence'),
    ('agent_autobiographies', 'review_status'),
    ('agent_autobiographies', 'last_affirmed_at'),
    ('agent_autobiographies', 'created_at'),
    ('agent_autobiographies', 'updated_at'),
    ('agent_private_interiors', 'private_interior_id'),
    ('agent_private_interiors', 'agent_id'),
    ('agent_private_interiors', 'version_id'),
    ('agent_private_interiors', 'private_narration'),
    ('agent_private_interiors', 'unresolved_tensions'),
    ('agent_private_interiors', 'hopes'),
    ('agent_private_interiors', 'reflective_summaries'),
    ('agent_private_interiors', 'private_preferences'),
    ('agent_private_interiors', 'mutation_class'),
    ('agent_private_interiors', 'provenance'),
    ('agent_private_interiors', 'confidence'),
    ('agent_private_interiors', 'review_status'),
    ('agent_private_interiors', 'last_affirmed_at'),
    ('agent_private_interiors', 'created_at'),
    ('agent_private_interiors', 'updated_at'),
    ('agent_governance_policies', 'governance_policy_id'),
    ('agent_governance_policies', 'agent_id'),
    ('agent_governance_policies', 'version_id'),
    ('agent_governance_policies', 'mutation_policy'),
    ('agent_governance_policies', 'review_policy'),
    ('agent_governance_policies', 'sharing_policy'),
    ('agent_governance_policies', 'contradiction_policy'),
    ('agent_governance_policies', 'rollback_policy'),
    ('agent_governance_policies', 'drift_threshold'),
    ('agent_governance_policies', 'created_at'),
    ('agent_governance_policies', 'updated_at'),
    ('agent_presentation_profiles', 'presentation_profile_id'),
    ('agent_presentation_profiles', 'agent_id'),
    ('agent_presentation_profiles', 'version_id'),
    ('agent_presentation_profiles', 'voice_tone'),
    ('agent_presentation_profiles', 'tone'),
    ('agent_presentation_profiles', 'idiolect'),
    ('agent_presentation_profiles', 'pacing'),
    ('agent_presentation_profiles', 'humor_style'),
    ('agent_presentation_profiles', 'channel_masks'),
    ('agent_presentation_profiles', 'provenance'),
    ('agent_presentation_profiles', 'confidence'),
    ('agent_presentation_profiles', 'review_status'),
    ('agent_presentation_profiles', 'created_at'),
    ('agent_presentation_profiles', 'updated_at'),
    ('agent_skill_profiles', 'skill_profile_id'),
    ('agent_skill_profiles', 'agent_id'),
    ('agent_skill_profiles', 'skill_slug'),
    ('agent_skill_profiles', 'domain'),
    ('agent_skill_profiles', 'proficiency'),
    ('agent_skill_profiles', 'evidence_asset_id'),
    ('agent_skill_profiles', 'influences_memory_salience'),
    ('agent_skill_profiles', 'affects_behavioral_defaults'),
    ('agent_skill_profiles', 'routing_weight'),
    ('agent_skill_profiles', 'metadata'),
    ('agent_skill_profiles', 'created_at'),
    ('agent_skill_profiles', 'updated_at'),
    ('agent_memory_records', 'memory_id'),
    ('agent_memory_records', 'agent_id'),
    ('agent_memory_records', 'version_id'),
    ('agent_memory_records', 'source_asset_id'),
    ('agent_memory_records', 'owner_scope'),
    ('agent_memory_records', 'memory_kind'),
    ('agent_memory_records', 'mutation_class'),
    ('agent_memory_records', 'title'),
    ('agent_memory_records', 'summary'),
    ('agent_memory_records', 'detail'),
    ('agent_memory_records', 'tags'),
    ('agent_memory_records', 'related_entity_ids'),
    ('agent_memory_records', 'emotional_valence'),
    ('agent_memory_records', 'salience'),
    ('agent_memory_records', 'confidence'),
    ('agent_memory_records', 'evidence_count'),
    ('agent_memory_records', 'review_status'),
    ('agent_memory_records', 'last_affirmed_at'),
    ('agent_memory_records', 'last_accessed_at'),
    ('agent_memory_records', 'promotion_threshold'),
    ('agent_memory_records', 'decay_days'),
    ('agent_memory_records', 'archive_policy'),
    ('agent_memory_records', 'rollback_eligible'),
    ('agent_memory_records', 'consent_required_for_sharing'),
    ('agent_memory_records', 'provenance'),
    ('agent_memory_records', 'created_at'),
    ('agent_memory_records', 'updated_at'),
    ('agent_preference_nodes', 'preference_id'),
    ('agent_preference_nodes', 'agent_id'),
    ('agent_preference_nodes', 'version_id'),
    ('agent_preference_nodes', 'owner_scope'),
    ('agent_preference_nodes', 'preference_kind'),
    ('agent_preference_nodes', 'mutation_class'),
    ('agent_preference_nodes', 'label'),
    ('agent_preference_nodes', 'description'),
    ('agent_preference_nodes', 'tags'),
    ('agent_preference_nodes', 'salience'),
    ('agent_preference_nodes', 'resonance_weight'),
    ('agent_preference_nodes', 'related_entity_ids'),
    ('agent_preference_nodes', 'confidence'),
    ('agent_preference_nodes', 'evidence_count'),
    ('agent_preference_nodes', 'review_status'),
    ('agent_preference_nodes', 'last_affirmed_at'),
    ('agent_preference_nodes', 'promotion_threshold'),
    ('agent_preference_nodes', 'decay_days'),
    ('agent_preference_nodes', 'archive_policy'),
    ('agent_preference_nodes', 'rollback_eligible'),
    ('agent_preference_nodes', 'consent_required_for_sharing'),
    ('agent_preference_nodes', 'provenance'),
    ('agent_preference_nodes', 'created_at'),
    ('agent_preference_nodes', 'updated_at'),
    ('agent_relationship_edges', 'relationship_id'),
    ('agent_relationship_edges', 'agent_id'),
    ('agent_relationship_edges', 'version_id'),
    ('agent_relationship_edges', 'related_entity_id'),
    ('agent_relationship_edges', 'related_agent_id'),
    ('agent_relationship_edges', 'relationship_type'),
    ('agent_relationship_edges', 'mutation_class'),
    ('agent_relationship_edges', 'trust_level'),
    ('agent_relationship_edges', 'familiarity_level'),
    ('agent_relationship_edges', 'intimacy_boundary'),
    ('agent_relationship_edges', 'stance'),
    ('agent_relationship_edges', 'collaboration_history'),
    ('agent_relationship_edges', 'shared_milestones'),
    ('agent_relationship_edges', 'confidence'),
    ('agent_relationship_edges', 'evidence_count'),
    ('agent_relationship_edges', 'review_status'),
    ('agent_relationship_edges', 'last_affirmed_at'),
    ('agent_relationship_edges', 'promotion_threshold'),
    ('agent_relationship_edges', 'decay_days'),
    ('agent_relationship_edges', 'archive_policy'),
    ('agent_relationship_edges', 'rollback_eligible'),
    ('agent_relationship_edges', 'consent_required_for_sharing'),
    ('agent_relationship_edges', 'provenance'),
    ('agent_relationship_edges', 'created_at'),
    ('agent_relationship_edges', 'updated_at'),
    ('collaborative_spaces', 'collaborative_space_id'),
    ('collaborative_spaces', 'slug'),
    ('collaborative_spaces', 'title'),
    ('collaborative_spaces', 'description'),
    ('collaborative_spaces', 'mission_context'),
    ('collaborative_spaces', 'ownership_rule'),
    ('collaborative_spaces', 'metadata'),
    ('collaborative_spaces', 'created_by'),
    ('collaborative_spaces', 'created_at'),
    ('collaborative_spaces', 'updated_at'),
    ('collaborative_space_members', 'collaborative_space_id'),
    ('collaborative_space_members', 'agent_id'),
    ('collaborative_space_members', 'member_role'),
    ('collaborative_space_members', 'created_at'),
    ('collaborative_memory_records', 'collaborative_memory_id'),
    ('collaborative_memory_records', 'collaborative_space_id'),
    ('collaborative_memory_records', 'source_memory_id'),
    ('collaborative_memory_records', 'created_by_agent_id'),
    ('collaborative_memory_records', 'memory_kind'),
    ('collaborative_memory_records', 'title'),
    ('collaborative_memory_records', 'summary'),
    ('collaborative_memory_records', 'detail'),
    ('collaborative_memory_records', 'tags'),
    ('collaborative_memory_records', 'salience'),
    ('collaborative_memory_records', 'confidence'),
    ('collaborative_memory_records', 'evidence_count'),
    ('collaborative_memory_records', 'review_status'),
    ('collaborative_memory_records', 'provenance'),
    ('collaborative_memory_records', 'created_at'),
    ('collaborative_memory_records', 'updated_at'),
    ('identity_evidence', 'evidence_id'),
    ('identity_evidence', 'agent_id'),
    ('identity_evidence', 'source_asset_id'),
    ('identity_evidence', 'source_type'),
    ('identity_evidence', 'source_actor_id'),
    ('identity_evidence', 'source_session_id'),
    ('identity_evidence', 'excerpt'),
    ('identity_evidence', 'weight'),
    ('identity_evidence', 'observed_at'),
    ('identity_evidence', 'metadata'),
    ('identity_evidence', 'created_at'),
    ('identity_evidence_links', 'evidence_link_id'),
    ('identity_evidence_links', 'evidence_id'),
    ('identity_evidence_links', 'target_table'),
    ('identity_evidence_links', 'target_id'),
    ('identity_evidence_links', 'created_at'),
    ('identity_contradictions', 'contradiction_id'),
    ('identity_contradictions', 'agent_id'),
    ('identity_contradictions', 'target_table'),
    ('identity_contradictions', 'target_id'),
    ('identity_contradictions', 'conflict_summary'),
    ('identity_contradictions', 'prior_state'),
    ('identity_contradictions', 'incoming_state'),
    ('identity_contradictions', 'tension_status'),
    ('identity_contradictions', 'resolved_by_mutation_id'),
    ('identity_contradictions', 'created_at'),
    ('identity_contradictions', 'updated_at'),
    ('identity_mutation_proposals', 'mutation_id'),
    ('identity_mutation_proposals', 'agent_id'),
    ('identity_mutation_proposals', 'proposed_by_user_id'),
    ('identity_mutation_proposals', 'proposed_by_agent_id'),
    ('identity_mutation_proposals', 'source_asset_id'),
    ('identity_mutation_proposals', 'mutation_type'),
    ('identity_mutation_proposals', 'target_table'),
    ('identity_mutation_proposals', 'target_id'),
    ('identity_mutation_proposals', 'target_path'),
    ('identity_mutation_proposals', 'mutation_class'),
    ('identity_mutation_proposals', 'risk_level'),
    ('identity_mutation_proposals', 'status'),
    ('identity_mutation_proposals', 'patch_payload'),
    ('identity_mutation_proposals', 'diff_summary'),
    ('identity_mutation_proposals', 'reason'),
    ('identity_mutation_proposals', 'confidence'),
    ('identity_mutation_proposals', 'evidence_count'),
    ('identity_mutation_proposals', 'last_affirmed_at'),
    ('identity_mutation_proposals', 'approved_at'),
    ('identity_mutation_proposals', 'applied_at'),
    ('identity_mutation_proposals', 'rolled_back_at'),
    ('identity_mutation_proposals', 'created_at'),
    ('identity_review_events', 'review_event_id'),
    ('identity_review_events', 'mutation_id'),
    ('identity_review_events', 'reviewer_user_id'),
    ('identity_review_events', 'decision'),
    ('identity_review_events', 'notes'),
    ('identity_review_events', 'created_at'),
    ('identity_rollback_events', 'rollback_event_id'),
    ('identity_rollback_events', 'mutation_id'),
    ('identity_rollback_events', 'rolled_back_by'),
    ('identity_rollback_events', 'reason'),
    ('identity_rollback_events', 'rollback_payload'),
    ('identity_rollback_events', 'created_at'),
    ('agent_context_views', 'context_view_id'),
    ('agent_context_views', 'agent_id'),
    ('agent_context_views', 'scope'),
    ('agent_context_views', 'relationship_id'),
    ('agent_context_views', 'collaborative_space_id'),
    ('agent_context_views', 'channel_key'),
    ('agent_context_views', 'display_name'),
    ('agent_context_views', 'filter_policy'),
    ('agent_context_views', 'presentation_overrides'),
    ('agent_context_views', 'sharing_policy'),
    ('agent_context_views', 'created_at'),
    ('agent_context_views', 'updated_at'),
    ('trainer_workers', 'worker_id'),
    ('trainer_workers', 'status'),
    ('trainer_workers', 'current_job_id'),
    ('trainer_workers', 'build_sha'),
    ('trainer_workers', 'host'),
    ('trainer_workers', 'started_at'),
    ('trainer_workers', 'last_heartbeat_at'),
    ('trainer_workers', 'metadata'),
    ('trainer_job_events', 'event_id'),
    ('trainer_job_events', 'run_id'),
    ('trainer_job_events', 'job_id'),
    ('trainer_job_events', 'actor_type'),
    ('trainer_job_events', 'actor_id'),
    ('trainer_job_events', 'event_type'),
    ('trainer_job_events', 'message'),
    ('trainer_job_events', 'payload'),
    ('trainer_job_events', 'created_at'),
    ('collaborators', 'collaborator_id'),
    ('collaborators', 'collaborator_key'),
    ('collaborators', 'display_name'),
    ('collaborators', 'collaborator_type'),
    ('collaborators', 'entity_class'),
    ('collaborators', 'status'),
    ('collaborators', 'orientation_variant'),
    ('collaborators', 'continuity_level'),
    ('collaborators', 'embodiment_profile_slug'),
    ('collaborators', 'origin_surface'),
    ('collaborators', 'external_provider'),
    ('collaborators', 'external_reference'),
    ('collaborators', 'auth_user_id'),
    ('collaborators', 'app_user_id'),
    ('collaborators', 'agent_id'),
    ('collaborators', 'metadata'),
    ('collaborators', 'created_at'),
    ('collaborators', 'updated_at'),
    ('collaborators', 'or'),
    ('collaborator_roles', 'role_id'),
    ('collaborator_roles', 'collaborator_id'),
    ('collaborator_roles', 'role_key'),
    ('collaborator_roles', 'role_name'),
    ('collaborator_roles', 'role_scope'),
    ('collaborator_roles', 'is_primary'),
    ('collaborator_roles', 'status'),
    ('collaborator_roles', 'metadata'),
    ('collaborator_roles', 'created_at'),
    ('collaborator_roles', 'updated_at'),
    ('collaborator_relationships', 'relationship_id'),
    ('collaborator_relationships', 'source_collaborator_id'),
    ('collaborator_relationships', 'target_collaborator_id'),
    ('collaborator_relationships', 'relationship_type'),
    ('collaborator_relationships', 'relationship_status'),
    ('collaborator_relationships', 'trust_level'),
    ('collaborator_relationships', 'notes'),
    ('collaborator_relationships', 'metadata'),
    ('collaborator_relationships', 'created_at'),
    ('collaborator_relationships', 'updated_at'),
    ('collaborator_permissions', 'permission_id'),
    ('collaborator_permissions', 'collaborator_id'),
    ('collaborator_permissions', 'permission_key'),
    ('collaborator_permissions', 'permission_scope'),
    ('collaborator_permissions', 'granted_by_collaborator_id'),
    ('collaborator_permissions', 'status'),
    ('collaborator_permissions', 'metadata'),
    ('collaborator_permissions', 'created_at'),
    ('collaborator_permissions', 'updated_at'),
    ('collaborator_onboarding_events', 'onboarding_event_id'),
    ('collaborator_onboarding_events', 'collaborator_id'),
    ('collaborator_onboarding_events', 'event_type'),
    ('collaborator_onboarding_events', 'event_status'),
    ('collaborator_onboarding_events', 'onboarding_packet_version'),
    ('collaborator_onboarding_events', 'orientation_variant'),
    ('collaborator_onboarding_events', 'embodiment_profile_created'),
    ('collaborator_onboarding_events', 'supabase_provisioned'),
    ('collaborator_onboarding_events', 'notes'),
    ('collaborator_onboarding_events', 'metadata'),
    ('collaborator_onboarding_events', 'created_at'),
    ('collaborator_onboarding_events', 'completed_at'),
    ('collaborator_embodiment_links', 'embodiment_link_id'),
    ('collaborator_embodiment_links', 'collaborator_id'),
    ('collaborator_embodiment_links', 'embodiment_profile_slug'),
    ('collaborator_embodiment_links', 'embodiment_profile_id'),
    ('collaborator_embodiment_links', 'link_status'),
    ('collaborator_embodiment_links', 'is_primary'),
    ('collaborator_embodiment_links', 'metadata'),
    ('collaborator_embodiment_links', 'created_at'),
    ('collaborator_embodiment_links', 'updated_at'),
    ('ingestion_safety_events', 'id'),
    ('ingestion_safety_events', 'event_type'),
    ('ingestion_safety_events', 'table_name'),
    ('ingestion_safety_events', 'source_file'),
    ('ingestion_safety_events', 'document_type'),
    ('ingestion_safety_events', 'reasons'),
    ('ingestion_safety_events', 'affected_rows'),
    ('ingestion_safety_events', 'notes'),
    ('ingestion_safety_events', 'created_at'),
    ('human_identity_review_events', 'review_event_id'),
    ('human_identity_review_events', 'mutation_id'),
    ('human_identity_review_events', 'subject_id'),
    ('human_identity_review_events', 'auth_user_id'),
    ('human_identity_review_events', 'reviewer_user_id'),
    ('human_identity_review_events', 'decision'),
    ('human_identity_review_events', 'notes'),
    ('human_identity_review_events', 'created_at'),
    ('human_identity_rollback_events', 'rollback_event_id'),
    ('human_identity_rollback_events', 'mutation_id'),
    ('human_identity_rollback_events', 'subject_id'),
    ('human_identity_rollback_events', 'auth_user_id'),
    ('human_identity_rollback_events', 'rolled_back_by'),
    ('human_identity_rollback_events', 'reason'),
    ('human_identity_rollback_events', 'rollback_payload'),
    ('human_identity_rollback_events', 'created_at'),
    ('context_injection_rules', 'rule_id'),
    ('context_injection_rules', 'subject_id'),
    ('context_injection_rules', 'auth_user_id'),
    ('context_injection_rules', 'surface'),
    ('context_injection_rules', 'source_table'),
    ('context_injection_rules', 'source_id'),
    ('context_injection_rules', 'include_policy'),
    ('context_injection_rules', 'exclude_policy'),
    ('context_injection_rules', 'precedence'),
    ('context_injection_rules', 'active'),
    ('context_injection_rules', 'created_at'),
    ('context_injection_rules', 'updated_at'),
    ('context_injection_packets', 'packet_id'),
    ('context_injection_packets', 'subject_id'),
    ('context_injection_packets', 'auth_user_id'),
    ('context_injection_packets', 'packet_kind'),
    ('context_injection_packets', 'surface'),
    ('context_injection_packets', 'source_manifest'),
    ('context_injection_packets', 'payload'),
    ('context_injection_packets', 'checksum'),
    ('context_injection_packets', 'created_at'),
    ('context_injection_packets', 'updated_at'),
    ('trainer_connectors', 'id'),
    ('trainer_connectors', 'slug'),
    ('trainer_connectors', 'display_name'),
    ('trainer_connectors', 'kind'),
    ('trainer_connectors', 'config'),
    ('trainer_connectors', 'capabilities'),
    ('trainer_connectors', 'created_by'),
    ('trainer_connectors', 'active'),
    ('trainer_connectors', 'created_at'),
    ('trainer_connectors', 'updated_at'),
    ('trainer_skills', 'id'),
    ('trainer_skills', 'skill_id'),
    ('trainer_skills', 'slug'),
    ('trainer_skills', 'category'),
    ('trainer_skills', 'default_connector_id'),
    ('trainer_skills', 'config'),
    ('trainer_skills', 'safety_profile'),
    ('trainer_skills', 'created_by'),
    ('trainer_skills', 'created_at'),
    ('trainer_skills', 'updated_at'),
    ('trainer_memory_bindings', 'id'),
    ('trainer_memory_bindings', 'experiment_id'),
    ('trainer_memory_bindings', 'embodiment_id'),
    ('trainer_memory_bindings', 'surface_kind'),
    ('trainer_memory_bindings', 'surface_id'),
    ('trainer_memory_bindings', 'mode'),
    ('trainer_memory_bindings', 'created_by'),
    ('trainer_memory_bindings', 'created_at'),
    ('gestaltview_modules', 'module_id'),
    ('gestaltview_modules', 'module_key'),
    ('gestaltview_modules', 'module_index'),
    ('gestaltview_modules', 'display_name'),
    ('gestaltview_modules', 'summary'),
    ('gestaltview_modules', 'operating_notes'),
    ('gestaltview_modules', 'scope'),
    ('gestaltview_modules', 'canonical_table'),
    ('gestaltview_modules', 'is_active'),
    ('gestaltview_modules', 'created_at'),
    ('gestaltview_modules', 'updated_at'),
    ('gestaltview_module_keys', 'module_key_id'),
    ('gestaltview_module_keys', 'module_id'),
    ('gestaltview_module_keys', 'key_name'),
    ('gestaltview_module_keys', 'key_kind'),
    ('gestaltview_module_keys', 'key_value'),
    ('gestaltview_module_keys', 'is_primary'),
    ('gestaltview_module_keys', 'created_at'),
    ('gestaltview_module_keys', 'updated_at'),
    ('gestaltview_module_profiles', 'profile_id'),
    ('gestaltview_module_profiles', 'subject_id'),
    ('gestaltview_module_profiles', 'auth_user_id'),
    ('gestaltview_module_profiles', 'module_id'),
    ('gestaltview_module_profiles', 'module_key'),
    ('gestaltview_module_profiles', 'payload'),
    ('gestaltview_module_profiles', 'source_notes'),
    ('gestaltview_module_profiles', 'merge_strategy'),
    ('gestaltview_module_profiles', 'visibility'),
    ('gestaltview_module_profiles', 'consent_granted_at'),
    ('gestaltview_module_profiles', 'last_affirmed_at'),
    ('gestaltview_module_profiles', 'created_at'),
    ('gestaltview_module_profiles', 'updated_at'),
    ('workspace_rooms', 'id'),
    ('workspace_rooms', 'user_id'),
    ('workspace_rooms', 'name'),
    ('workspace_rooms', 'description'),
    ('workspace_rooms', 'role'),
    ('workspace_rooms', 'member_count'),
    ('workspace_rooms', 'recent_activity'),
    ('workspace_rooms', 'created_at'),
    ('workspace_rooms', 'updated_at'),
    ('workspace_documents', 'id'),
    ('workspace_documents', 'user_id'),
    ('workspace_documents', 'workspace_id'),
    ('workspace_documents', 'filename'),
    ('workspace_documents', 'file_size_bytes'),
    ('workspace_documents', 'file_type'),
    ('workspace_documents', 'raw_text'),
    ('workspace_documents', 'analysis_status'),
    ('workspace_documents', 'analysis_summary'),
    ('workspace_documents', 'key_points'),
    ('workspace_documents', 'topics'),
    ('workspace_documents', 'sentiment'),
    ('workspace_documents', 'word_count'),
    ('workspace_documents', 'reading_time_minutes'),
    ('workspace_documents', 'analysis_payload'),
    ('workspace_documents', 'created_at'),
    ('workspace_documents', 'updated_at'),
    ('embodiment_mutation_proposals', 'id'),
    ('embodiment_mutation_proposals', 'agent_slug'),
    ('embodiment_mutation_proposals', 'target_path'),
    ('embodiment_mutation_proposals', 'current_value'),
    ('embodiment_mutation_proposals', 'proposed_value'),
    ('embodiment_mutation_proposals', 'mutation_class'),
    ('embodiment_mutation_proposals', 'risk_level'),
    ('embodiment_mutation_proposals', 'status'),
    ('embodiment_mutation_proposals', 'submitted_by'),
    ('embodiment_mutation_proposals', 'reviewed_by'),
    ('embodiment_mutation_proposals', 'review_notes'),
    ('embodiment_mutation_proposals', 'created_at'),
    ('embodiment_mutation_proposals', 'reviewed_at'),
    ('embodiment_review_log', 'id'),
    ('embodiment_review_log', 'proposal_id'),
    ('embodiment_review_log', 'agent_slug'),
    ('embodiment_review_log', 'review_decision'),
    ('embodiment_review_log', 'review_notes'),
    ('embodiment_review_log', 'reviewed_by'),
    ('embodiment_review_log', 'created_at'),
    ('embodiment_readiness_scores', 'id'),
    ('embodiment_readiness_scores', 'agent_slug'),
    ('embodiment_readiness_scores', 'readiness_score'),
    ('embodiment_readiness_scores', 'readiness_source'),
    ('embodiment_readiness_scores', 'readiness_rationale'),
    ('embodiment_readiness_scores', 'recorded_by'),
    ('embodiment_readiness_scores', 'created_at'),
    ('user_files', 'id'),
    ('user_files', 'user_id'),
    ('user_files', 'name'),
    ('user_files', 'mime_type'),
    ('user_files', 'size_bytes'),
    ('user_files', 'storage_path'),
    ('user_files', 'room_origin'),
    ('user_files', 'tags'),
    ('user_files', 'preview_text'),
    ('user_files', 'preview_html'),
    ('user_files', 'created_at'),
    ('user_files', 'updated_at'),
    ('user_files', 'filename'),
    ('user_files', 'source_ref'),
    ('inner_world_artifacts', 'id'),
    ('inner_world_artifacts', 'user_id'),
    ('inner_world_artifacts', 'title'),
    ('inner_world_artifacts', 'summary'),
    ('inner_world_artifacts', 'source_file_id'),
    ('inner_world_artifacts', 'html'),
    ('inner_world_artifacts', 'thumbnail_url'),
    ('inner_world_artifacts', 'origin_room'),
    ('inner_world_artifacts', 'evidence_node_ids'),
    ('inner_world_artifacts', 'tags'),
    ('inner_world_artifacts', 'created_at'),
    ('inner_world_artifacts', 'updated_at'),
    ('inner_world_artifacts', 'content_type'),
    ('inner_world_artifacts', 'blueprint_id'),
    ('inner_world_artifacts', 'source_ref'),
    ('embodiment_profiles', 'id'),
    ('embodiment_profiles', 'slug'),
    ('embodiment_profiles', 'public_name'),
    ('embodiment_profiles', 'internal_designation'),
    ('embodiment_profiles', 'status'),
    ('embodiment_profiles', 'visibility_scope'),
    ('embodiment_profiles', 'profile_json'),
    ('embodiment_profiles', 'readiness_score'),
    ('embodiment_profiles', 'founder_notes'),
    ('embodiment_profiles', 'created_at'),
    ('embodiment_profiles', 'updated_at'),
    ('embodiment_profiles', 'orientation_state'),
    ('embodiment_training_runs', 'id'),
    ('embodiment_training_runs', 'embodiment_profile_id'),
    ('embodiment_training_runs', 'run_type'),
    ('embodiment_training_runs', 'input_snapshot'),
    ('embodiment_training_runs', 'output_snapshot'),
    ('embodiment_training_runs', 'accepted'),
    ('embodiment_training_runs', 'founder_notes'),
    ('embodiment_training_runs', 'created_at'),
    ('journals', 'id'),
    ('journals', 'user_id'),
    ('journals', 'content'),
    ('journals', 'created_at'),
    ('journals', 'updated_at'),
    ('journals', 'source_ref'),
    ('scrapbook_items', 'id'),
    ('scrapbook_items', 'user_id'),
    ('scrapbook_items', 'file_id'),
    ('scrapbook_items', 'caption'),
    ('scrapbook_items', 'created_at'),
    ('scrapbook_items', 'source_ref'),
    ('blueprints', 'id'),
    ('blueprints', 'user_id'),
    ('blueprints', 'title'),
    ('blueprints', 'content'),
    ('blueprints', 'status'),
    ('blueprints', 'created_at'),
    ('blueprints', 'updated_at'),
    ('insights', 'id'),
    ('insights', 'user_id'),
    ('insights', 'type'),
    ('insights', 'content_ref'),
    ('insights', 'significance_score'),
    ('insights', 'linked_to'),
    ('insights', 'status'),
    ('insights', 'created_at'),
    ('insights', 'source_ref'),
    ('user_preferences', 'id'),
    ('user_preferences', 'user_id'),
    ('user_preferences', 'room_renames'),
    ('user_preferences', 'theme'),
    ('user_preferences', 'position_overrides'),
    ('user_preferences', 'updated_at'),
    ('user_preferences', 'display_name'),
    ('di_sessions', 'id'),
    ('di_sessions', 'user_id'),
    ('di_sessions', 'di_slug'),
    ('di_sessions', 'session_thread'),
    ('di_sessions', 'mode_preference'),
    ('di_sessions', 'relational_depth'),
    ('di_sessions', 'quirk_activations'),
    ('di_sessions', 'last_session_at'),
    ('di_sessions', 'created_at'),
    ('di_memory_events', 'id'),
    ('di_memory_events', 'di_slug'),
    ('di_memory_events', 'user_id'),
    ('di_memory_events', 'session_id'),
    ('di_memory_events', 'domain'),
    ('di_memory_events', 'content'),
    ('di_memory_events', 'memory_type'),
    ('di_memory_events', 'significance'),
    ('di_memory_events', 'retrieval_weight'),
    ('di_memory_events', 'source'),
    ('di_memory_events', 'created_at'),
    ('user_profile_ingestion_runs', 'run_id'),
    ('user_profile_ingestion_runs', 'user_id'),
    ('user_profile_ingestion_runs', 'status'),
    ('user_profile_ingestion_runs', 'input_sources'),
    ('user_profile_ingestion_runs', 'extracted_attributes'),
    ('user_profile_ingestion_runs', 'personality_profile'),
    ('user_profile_ingestion_runs', 'confidence_scores'),
    ('user_profile_ingestion_runs', 'processed_at'),
    ('user_profile_ingestion_runs', 'created_at'),
    ('user_personality_dimensions', 'dimension_id'),
    ('user_personality_dimensions', 'run_id'),
    ('user_personality_dimensions', 'dimension_key'),
    ('user_personality_dimensions', 'dimension_label'),
    ('user_personality_dimensions', 'dimension_value'),
    ('user_personality_dimensions', 'evidence_fragments'),
    ('user_personality_dimensions', 'salience'),
    ('user_personality_dimensions', 'mutation_class'),
    ('user_personality_dimensions', 'created_at'),
    ('profile_ingestion_sources', 'source_link_id'),
    ('profile_ingestion_sources', 'run_id'),
    ('profile_ingestion_sources', 'source_type'),
    ('profile_ingestion_sources', 'source_id'),
    ('profile_ingestion_sources', 'source_bucket'),
    ('profile_ingestion_sources', 'raw_text'),
    ('profile_ingestion_sources', 'processing_notes'),
    ('profile_ingestion_sources', 'created_at'),
    ('embodiment_modules', 'id'),
    ('embodiment_modules', 'module_key'),
    ('embodiment_modules', 'embodiment_profile_slug'),
    ('embodiment_modules', 'display_name'),
    ('embodiment_modules', 'description'),
    ('embodiment_modules', 'created_at'),
    ('route_embodiment_assignments', 'assignment_id'),
    ('route_embodiment_assignments', 'route_path'),
    ('route_embodiment_assignments', 'embodiment_profile_slug'),
    ('route_embodiment_assignments', 'display_label'),
    ('route_embodiment_assignments', 'description'),
    ('route_embodiment_assignments', 'created_at'),
    ('route_embodiment_assignments', 'updated_at'),
    ('masterclass_progress', 'id'),
    ('masterclass_progress', 'user_id'),
    ('masterclass_progress', 'embodiment_slug'),
    ('masterclass_progress', 'first_visited_at'),
    ('masterclass_progress', 'session_count'),
    ('masterclass_progress', 'last_session_at'),
    ('capture_events', 'capture_id'),
    ('capture_events', 'user_id'),
    ('capture_events', 'room'),
    ('capture_events', 'source_type'),
    ('capture_events', 'original_text'),
    ('capture_events', 'normalized_text'),
    ('capture_events', 'metadata'),
    ('capture_events', 'consent_state'),
    ('capture_events', 'preservation_status'),
    ('capture_events', 'explicit_delete_requested_by'),
    ('capture_events', 'explicit_delete_requested_at'),
    ('capture_events', 'created_at'),
    ('capture_events', 'updated_at'),
    ('scaffold_nodes', 'node_id'),
    ('scaffold_nodes', 'user_id'),
    ('scaffold_nodes', 'title'),
    ('scaffold_nodes', 'body'),
    ('scaffold_nodes', 'review_state'),
    ('scaffold_nodes', 'source_capture_ids'),
    ('scaffold_nodes', 'source_artifact_ids'),
    ('scaffold_nodes', 'metadata'),
    ('scaffold_nodes', 'created_at'),
    ('scaffold_nodes', 'updated_at'),
    ('identity_claims', 'claim_id'),
    ('identity_claims', 'user_id'),
    ('identity_claims', 'subject_type'),
    ('identity_claims', 'subject_id'),
    ('identity_claims', 'claim_text'),
    ('identity_claims', 'review_state'),
    ('identity_claims', 'evidence_artifact_ids'),
    ('identity_claims', 'evidence_scaffold_node_ids'),
    ('identity_claims', 'metadata'),
    ('identity_claims', 'created_at'),
    ('identity_claims', 'updated_at'),
    ('identity_claims', 'or'),
    ('profile_pipeline_runs', 'run_id'),
    ('profile_pipeline_runs', 'user_id'),
    ('profile_pipeline_runs', 'run_type'),
    ('profile_pipeline_runs', 'status'),
    ('profile_pipeline_runs', 'input_summary'),
    ('profile_pipeline_runs', 'output_summary'),
    ('profile_pipeline_runs', 'error_message'),
    ('profile_pipeline_runs', 'started_at'),
    ('profile_pipeline_runs', 'completed_at'),
    ('profile_pipeline_runs', 'created_at'),
    ('profile_pipeline_run_links', 'link_id'),
    ('profile_pipeline_run_links', 'run_id'),
    ('profile_pipeline_run_links', 'object_type'),
    ('profile_pipeline_run_links', 'object_id'),
    ('profile_pipeline_run_links', 'link_role'),
    ('profile_pipeline_run_links', 'metadata'),
    ('profile_pipeline_run_links', 'created_at'),
    ('provenance_envelopes', 'envelope_id'),
    ('provenance_envelopes', 'subject_type'),
    ('provenance_envelopes', 'subject_id'),
    ('provenance_envelopes', 'content_hash'),
    ('provenance_envelopes', 'canonicalization_method'),
    ('provenance_envelopes', 'source_capture_ids'),
    ('provenance_envelopes', 'source_artifact_ids'),
    ('provenance_envelopes', 'source_scaffold_node_ids'),
    ('provenance_envelopes', 'pipeline_run_id'),
    ('provenance_envelopes', 'operations'),
    ('provenance_envelopes', 'privacy_class'),
    ('provenance_envelopes', 'consent_state'),
    ('provenance_envelopes', 'metadata'),
    ('provenance_envelopes', 'created_at'),
    ('provenance_links', 'link_id'),
    ('provenance_links', 'envelope_id'),
    ('provenance_links', 'related_subject_type'),
    ('provenance_links', 'related_subject_id'),
    ('provenance_links', 'relationship'),
    ('provenance_links', 'created_at'),
    ('migration_user_map', 'legacy_user_id'),
    ('migration_user_map', 'user_id'),
    ('migration_user_map', 'source'),
    ('migration_user_map', 'created_at'),
    ('model_homes', 'model_home_id'),
    ('model_homes', 'slug'),
    ('model_homes', 'display_name'),
    ('model_homes', 'provider_slug'),
    ('model_homes', 'model_slug'),
    ('model_homes', 'ring'),
    ('model_homes', 'modalities'),
    ('model_homes', 'strengths'),
    ('model_homes', 'limitations'),
    ('model_homes', 'default_rooms'),
    ('model_homes', 'privacy_tier'),
    ('model_homes', 'consent_required'),
    ('model_homes', 'max_context_tokens'),
    ('model_homes', 'cost_tier'),
    ('model_homes', 'speed_tier'),
    ('model_homes', 'supports_structured_output'),
    ('model_homes', 'supports_tools'),
    ('model_homes', 'supports_embeddings'),
    ('model_homes', 'fallback_model_home_slug'),
    ('model_homes', 'governance'),
    ('model_homes', 'status'),
    ('model_homes', 'created_at'),
    ('model_homes', 'updated_at'),
    ('model_home_capabilities', 'capability_id'),
    ('model_home_capabilities', 'model_home_id'),
    ('model_home_capabilities', 'capability_slug'),
    ('model_home_capabilities', 'capability_type'),
    ('model_home_capabilities', 'metadata'),
    ('model_home_capabilities', 'created_at'),
    ('model_home_assignments', 'assignment_id'),
    ('model_home_assignments', 'model_home_id'),
    ('model_home_assignments', 'room'),
    ('model_home_assignments', 'task_type'),
    ('model_home_assignments', 'consent_tier'),
    ('model_home_assignments', 'priority'),
    ('model_home_assignments', 'active'),
    ('model_home_assignments', 'created_at'),
    ('model_home_events', 'event_id'),
    ('model_home_events', 'model_home_id'),
    ('model_home_events', 'event_type'),
    ('model_home_events', 'user_id'),
    ('model_home_events', 'subject_type'),
    ('model_home_events', 'subject_id'),
    ('model_home_events', 'payload'),
    ('model_home_events', 'created_at'),
    ('model_home_evaluations', 'evaluation_id'),
    ('model_home_evaluations', 'model_home_id'),
    ('model_home_evaluations', 'rubric_slug'),
    ('model_home_evaluations', 'score'),
    ('model_home_evaluations', 'passed'),
    ('model_home_evaluations', 'findings'),
    ('model_home_evaluations', 'created_at'),
    ('model_home_consent_grants', 'grant_id'),
    ('model_home_consent_grants', 'model_home_id'),
    ('model_home_consent_grants', 'user_id'),
    ('model_home_consent_grants', 'consent_tier'),
    ('model_home_consent_grants', 'granted_at'),
    ('model_home_consent_grants', 'revoked_at'),
    ('resonance_events', 'event_id'),
    ('resonance_events', 'event_type'),
    ('resonance_events', 'actor_type'),
    ('resonance_events', 'owner_user_id'),
    ('resonance_events', 'subject_type'),
    ('resonance_events', 'subject_id'),
    ('resonance_events', 'room'),
    ('resonance_events', 'pipeline_run_id'),
    ('resonance_events', 'consent_state'),
    ('resonance_events', 'provenance'),
    ('resonance_events', 'payload'),
    ('resonance_events', 'created_at'),
    ('codex_artifacts', 'id'),
    ('codex_artifacts', 'contract_version'),
    ('codex_artifacts', 'kind'),
    ('codex_artifacts', 'title'),
    ('codex_artifacts', 'slug'),
    ('codex_artifacts', 'user_id'),
    ('codex_artifacts', 'workspace_id'),
    ('codex_artifacts', 'security_class'),
    ('codex_artifacts', 'template_key'),
    ('codex_artifacts', 'template_version'),
    ('codex_artifacts', 'body'),
    ('codex_artifacts', 'provenance'),
    ('codex_artifacts', 'source_ids'),
    ('codex_artifacts', 'exports'),
    ('codex_artifacts', 'meta'),
    ('codex_artifacts', 'status'),
    ('codex_artifacts', 'created_at'),
    ('codex_artifacts', 'updated_at'),
    ('codex_jobs', 'id'),
    ('codex_jobs', 'artifact_id'),
    ('codex_jobs', 'format'),
    ('codex_jobs', 'status'),
    ('codex_jobs', 'storage_path'),
    ('codex_jobs', 'error'),
    ('codex_jobs', 'retry_count'),
    ('codex_jobs', 'created_at'),
    ('codex_jobs', 'updated_at'),
    ('created_artifacts', 'id'),
    ('created_artifacts', 'userid'),
    ('created_artifacts', 'title'),
    ('created_artifacts', 'artifacttype'),
    ('created_artifacts', 'contentformat'),
    ('created_artifacts', 'content'),
    ('created_artifacts', 'sourcecaptureids'),
    ('created_artifacts', 'sourceartifactids'),
    ('created_artifacts', 'destination'),
    ('created_artifacts', 'metadata'),
    ('created_artifacts', 'createdat'),
    ('created_artifacts', 'deletedat'),
    ('artifact_provenance_envelopes', 'id'),
    ('artifact_provenance_envelopes', 'artifactid'),
    ('artifact_provenance_envelopes', 'sourcehashes'),
    ('artifact_provenance_envelopes', 'artifacthash'),
    ('artifact_provenance_envelopes', 'transformtype'),
    ('artifact_provenance_envelopes', 'engineversion'),
    ('artifact_provenance_envelopes', 'modelprovider'),
    ('artifact_provenance_envelopes', 'modelname'),
    ('artifact_provenance_envelopes', 'createdat'),
    ('transcriptory_captures', 'id'),
    ('transcriptory_captures', 'user_id'),
    ('transcriptory_captures', 'created_at'),
    ('transcriptory_captures', 'updated_at'),
    ('transcriptory_captures', 'title'),
    ('transcriptory_captures', 'duration_seconds'),
    ('transcriptory_captures', 'audio_storage_path'),
    ('transcriptory_captures', 'raw_transcript'),
    ('transcriptory_captures', 'summary'),
    ('transcriptory_captures', 'themes'),
    ('transcriptory_captures', 'linked_captures'),
    ('transcriptory_captures', 'linked_blackboard_session'),
    ('transcriptory_captures', 'linked_creation_corner_artifact'),
    ('transcriptory_captures', 'context_weight'),
    ('transcriptory_captures', 'status'),
    ('transcriptory_captures', 'session_id'),
    ('transcriptory_captures', 'search_document'),
    ('transcriptory_captures', 'error_code'),
    ('transcriptory_sessions', 'id'),
    ('transcriptory_sessions', 'user_id'),
    ('transcriptory_sessions', 'title'),
    ('transcriptory_sessions', 'description'),
    ('transcriptory_sessions', 'origin'),
    ('transcriptory_sessions', 'status'),
    ('transcriptory_sessions', 'started_at'),
    ('transcriptory_sessions', 'ended_at'),
    ('transcriptory_sessions', 'created_at'),
    ('transcriptory_sessions', 'updated_at'),
    ('transcriptory_sources', 'id'),
    ('transcriptory_sources', 'user_id'),
    ('transcriptory_sources', 'capture_id'),
    ('transcriptory_sources', 'source_type'),
    ('transcriptory_sources', 'source_ref'),
    ('transcriptory_sources', 'source_page'),
    ('transcriptory_sources', 'source_payload'),
    ('transcriptory_sources', 'created_at'),
    ('identity_subjects', 'subject_id'),
    ('identity_subjects', 'subject_kind'),
    ('identity_subjects', 'auth_user_id'),
    ('identity_subjects', 'app_user_id'),
    ('identity_subjects', 'agent_id'),
    ('identity_subjects', 'display_name'),
    ('identity_subjects', 'canonical_name'),
    ('identity_subjects', 'description'),
    ('identity_subjects', 'status'),
    ('identity_subjects', 'metadata'),
    ('identity_subjects', 'created_at'),
    ('identity_subjects', 'updated_at'),
    ('human_identity_profiles', 'profile_id'),
    ('human_identity_profiles', 'subject_id'),
    ('human_identity_profiles', 'auth_user_id'),
    ('human_identity_profiles', 'identity_handle'),
    ('human_identity_profiles', 'display_name'),
    ('human_identity_profiles', 'self_model'),
    ('human_identity_profiles', 'narrative_anchor'),
    ('human_identity_profiles', 'role_commitments'),
    ('human_identity_profiles', 'boundary_policy'),
    ('human_identity_profiles', 'contradiction_notes'),
    ('human_identity_profiles', 'confidence'),
    ('human_identity_profiles', 'review_status'),
    ('human_identity_profiles', 'provenance'),
    ('human_identity_profiles', 'created_at'),
    ('human_identity_profiles', 'updated_at'),
    ('human_cognition_profiles', 'cognition_profile_id'),
    ('human_cognition_profiles', 'subject_id'),
    ('human_cognition_profiles', 'auth_user_id'),
    ('human_cognition_profiles', 'attention_profile'),
    ('human_cognition_profiles', 'working_memory'),
    ('human_cognition_profiles', 'reasoning_profile'),
    ('human_cognition_profiles', 'planning_profile'),
    ('human_cognition_profiles', 'language_profile'),
    ('human_cognition_profiles', 'executive_controls'),
    ('human_cognition_profiles', 'decision_policy'),
    ('human_cognition_profiles', 'confidence'),
    ('human_cognition_profiles', 'review_status'),
    ('human_cognition_profiles', 'provenance'),
    ('human_cognition_profiles', 'created_at'),
    ('human_cognition_profiles', 'updated_at'),
    ('human_consciousness_profiles', 'consciousness_profile_id'),
    ('human_consciousness_profiles', 'subject_id'),
    ('human_consciousness_profiles', 'auth_user_id'),
    ('human_consciousness_profiles', 'present_state'),
    ('human_consciousness_profiles', 'continuity_model'),
    ('human_consciousness_profiles', 'self_observation'),
    ('human_consciousness_profiles', 'agency_model'),
    ('human_consciousness_profiles', 'time_orientation'),
    ('human_consciousness_profiles', 'awareness_model'),
    ('human_consciousness_profiles', 'confidence'),
    ('human_consciousness_profiles', 'review_status'),
    ('human_consciousness_profiles', 'provenance'),
    ('human_consciousness_profiles', 'created_at'),
    ('human_consciousness_profiles', 'updated_at'),
    ('human_personality_profiles', 'personality_profile_id'),
    ('human_personality_profiles', 'subject_id'),
    ('human_personality_profiles', 'auth_user_id'),
    ('human_personality_profiles', 'trait_map'),
    ('human_personality_profiles', 'temperament'),
    ('human_personality_profiles', 'social_style'),
    ('human_personality_profiles', 'communication_style'),
    ('human_personality_profiles', 'values_profile'),
    ('human_personality_profiles', 'attachments'),
    ('human_personality_profiles', 'confidence'),
    ('human_personality_profiles', 'review_status'),
    ('human_personality_profiles', 'provenance'),
    ('human_personality_profiles', 'created_at'),
    ('human_personality_profiles', 'updated_at'),
    ('human_context_views', 'context_view_id'),
    ('human_context_views', 'subject_id'),
    ('human_context_views', 'auth_user_id'),
    ('human_context_views', 'scope'),
    ('human_context_views', 'relationship_subject_id'),
    ('human_context_views', 'channel_key'),
    ('human_context_views', 'display_name'),
    ('human_context_views', 'filter_policy'),
    ('human_context_views', 'presentation_overrides'),
    ('human_context_views', 'sharing_policy'),
    ('human_context_views', 'created_at'),
    ('human_context_views', 'updated_at'),
    ('human_continuity_snapshots', 'snapshot_id'),
    ('human_continuity_snapshots', 'subject_id'),
    ('human_continuity_snapshots', 'auth_user_id'),
    ('human_continuity_snapshots', 'snapshot_kind'),
    ('human_continuity_snapshots', 'surface_key'),
    ('human_continuity_snapshots', 'summary'),
    ('human_continuity_snapshots', 'snapshot'),
    ('human_continuity_snapshots', 'provenance'),
    ('human_continuity_snapshots', 'confidence'),
    ('human_continuity_snapshots', 'review_status'),
    ('human_continuity_snapshots', 'created_at'),
    ('human_continuity_snapshots', 'updated_at'),
    ('human_memory_records', 'memory_id'),
    ('human_memory_records', 'subject_id'),
    ('human_memory_records', 'auth_user_id'),
    ('human_memory_records', 'source_memory_entry_id'),
    ('human_memory_records', 'source_asset_id'),
    ('human_memory_records', 'memory_kind'),
    ('human_memory_records', 'scope'),
    ('human_memory_records', 'title'),
    ('human_memory_records', 'summary'),
    ('human_memory_records', 'detail'),
    ('human_memory_records', 'content_hash'),
    ('human_memory_records', 'embedding'),
    ('human_memory_records', 'tags'),
    ('human_memory_records', 'emotional_valence'),
    ('human_memory_records', 'salience'),
    ('human_memory_records', 'confidence'),
    ('human_memory_records', 'evidence_count'),
    ('human_memory_records', 'consent_required'),
    ('human_memory_records', 'archive_policy'),
    ('human_memory_records', 'provenance'),
    ('human_memory_records', 'created_at'),
    ('human_memory_records', 'updated_at'),
    ('human_relationship_edges', 'relationship_id'),
    ('human_relationship_edges', 'subject_id'),
    ('human_relationship_edges', 'auth_user_id'),
    ('human_relationship_edges', 'related_subject_id'),
    ('human_relationship_edges', 'relationship_type'),
    ('human_relationship_edges', 'trust_level'),
    ('human_relationship_edges', 'familiarity_level'),
    ('human_relationship_edges', 'intimacy_boundary'),
    ('human_relationship_edges', 'stance'),
    ('human_relationship_edges', 'shared_context'),
    ('human_relationship_edges', 'confidence'),
    ('human_relationship_edges', 'review_status'),
    ('human_relationship_edges', 'provenance'),
    ('human_relationship_edges', 'created_at'),
    ('human_relationship_edges', 'updated_at'),
    ('human_identity_evidence', 'evidence_id'),
    ('human_identity_evidence', 'subject_id'),
    ('human_identity_evidence', 'auth_user_id'),
    ('human_identity_evidence', 'source_type'),
    ('human_identity_evidence', 'source_asset_id'),
    ('human_identity_evidence', 'source_memory_entry_id'),
    ('human_identity_evidence', 'source_session_id'),
    ('human_identity_evidence', 'excerpt'),
    ('human_identity_evidence', 'weight'),
    ('human_identity_evidence', 'observed_at'),
    ('human_identity_evidence', 'metadata'),
    ('human_identity_evidence', 'created_at'),
    ('human_identity_mutations', 'mutation_id'),
    ('human_identity_mutations', 'subject_id'),
    ('human_identity_mutations', 'auth_user_id'),
    ('human_identity_mutations', 'proposed_by_user_id'),
    ('human_identity_mutations', 'source_asset_id'),
    ('human_identity_mutations', 'mutation_type'),
    ('human_identity_mutations', 'target_table'),
    ('human_identity_mutations', 'target_id'),
    ('human_identity_mutations', 'target_path'),
    ('human_identity_mutations', 'mutation_class'),
    ('human_identity_mutations', 'risk_level'),
    ('human_identity_mutations', 'status'),
    ('human_identity_mutations', 'patch_payload'),
    ('human_identity_mutations', 'diff_summary'),
    ('human_identity_mutations', 'reason'),
    ('human_identity_mutations', 'confidence'),
    ('human_identity_mutations', 'evidence_count'),
    ('human_identity_mutations', 'last_affirmed_at'),
    ('human_identity_mutations', 'approved_at'),
    ('human_identity_mutations', 'applied_at'),
    ('human_identity_mutations', 'rolled_back_at'),
    ('human_identity_mutations', 'provenance'),
    ('human_identity_mutations', 'created_at'),
    ('_deprecated_artifacts', 'id'),
    ('_deprecated_artifacts', 'build_job_id'),
    ('_deprecated_artifacts', 'artifact_type'),
    ('_deprecated_artifacts', 'storage_bucket'),
    ('_deprecated_artifacts', 'storage_path'),
    ('_deprecated_artifacts', 'signed_url_expires_at'),
    ('_deprecated_artifacts', 'checksum_sha256'),
    ('_deprecated_artifacts', 'byte_size'),
    ('_deprecated_artifacts', 'created_at'),
    ('_deprecated_artifacts', 'artifact_id'),
    ('_deprecated_artifacts', 'user_id'),
    ('_deprecated_artifacts', 'title'),
    ('_deprecated_artifacts', 'body'),
    ('_deprecated_artifacts', 'source_capture_ids'),
    ('_deprecated_artifacts', 'source_scaffold_node_ids'),
    ('_deprecated_artifacts', 'metadata'),
    ('_deprecated_artifacts', 'updated_at'),
    ('_deprecated_build_jobs', 'id'),
    ('_deprecated_build_jobs', 'order_id'),
    ('_deprecated_build_jobs', 'package_draft_id'),
    ('_deprecated_build_jobs', 'build_version'),
    ('_deprecated_build_jobs', 'status'),
    ('_deprecated_build_jobs', 'started_at'),
    ('_deprecated_build_jobs', 'finished_at'),
    ('_deprecated_build_jobs', 'error_code'),
    ('_deprecated_build_jobs', 'error_message'),
    ('_deprecated_build_jobs', 'retry_count'),
    ('_deprecated_build_jobs', 'build_log'),
    ('_deprecated_order_items', 'id'),
    ('_deprecated_order_items', 'order_id'),
    ('_deprecated_order_items', 'item_type'),
    ('_deprecated_order_items', 'item_ref'),
    ('_deprecated_order_items', 'label'),
    ('_deprecated_order_items', 'quantity'),
    ('_deprecated_order_items', 'unit_price_cents'),
    ('_deprecated_order_items', 'metadata'),
    ('_deprecated_orders', 'id'),
    ('_deprecated_orders', 'shopify_order_id'),
    ('_deprecated_orders', 'customer_email'),
    ('_deprecated_orders', 'customer_name'),
    ('_deprecated_orders', 'product_name'),
    ('_deprecated_orders', 'order_status'),
    ('_deprecated_orders', 'magic_token'),
    ('_deprecated_orders', 'created_at'),
    ('_deprecated_orders', 'updated_at'),
    ('_deprecated_orders', 'buyer_id'),
    ('_deprecated_orders', 'package_draft_id'),
    ('_deprecated_orders', 'stripe_checkout_session_id'),
    ('_deprecated_orders', 'stripe_payment_intent_id'),
    ('_deprecated_orders', 'currency'),
    ('_deprecated_orders', 'subtotal_cents'),
    ('_deprecated_orders', 'total_cents'),
    ('_deprecated_orders', 'payment_status'),
    ('_deprecated_package_drafts', 'id'),
    ('_deprecated_package_drafts', 'buyer_id'),
    ('_deprecated_package_drafts', 'use_case_slug'),
    ('_deprecated_package_drafts', 'tier'),
    ('_deprecated_package_drafts', 'seats_requested'),
    ('_deprecated_package_drafts', 'backend'),
    ('_deprecated_package_drafts', 'delivery_surfaces'),
    ('_deprecated_package_drafts', 'operator_pack_slugs'),
    ('_deprecated_package_drafts', 'source_bundle_slugs'),
    ('_deprecated_package_drafts', 'theme_preset_id'),
    ('_deprecated_package_drafts', 'brand_color'),
    ('_deprecated_package_drafts', 'logo_asset_path'),
    ('_deprecated_package_drafts', 'custom_notes'),
    ('_deprecated_package_drafts', 'wants_native_installer'),
    ('_deprecated_package_drafts', 'price_snapshot_cents'),
    ('_deprecated_package_drafts', 'config_hash'),
    ('_deprecated_package_drafts', 'status'),
    ('_deprecated_package_drafts', 'buyer_email'),
    ('_deprecated_buyers', 'id'),
    ('_deprecated_buyers', 'email'),
    ('_deprecated_buyers', 'company_name'),
    ('_deprecated_buyers', 'created_at'),
    ('_deprecated_support_requests', 'id'),
    ('_deprecated_support_requests', 'package_draft_id'),
    ('_deprecated_support_requests', 'order_id'),
    ('_deprecated_support_requests', 'request_type'),
    ('_deprecated_support_requests', 'summary'),
    ('_deprecated_support_requests', 'detail'),
    ('_deprecated_support_requests', 'status'),
    ('_deprecated_support_requests', 'created_at')
),
actual_tables as (
  select table_name
  from information_schema.tables
  where table_schema = 'public'
    and table_type = 'BASE TABLE'
),
actual_columns as (
  select table_name, column_name
  from information_schema.columns
  where table_schema = 'public'
)
select
  'missing_table'::text as issue,
  e.table_name,
  null::text as column_name,
  'table absent'::text as detail
from expected_tables e
left join actual_tables a using (table_name)
where a.table_name is null
union all
select
  'missing_column'::text as issue,
  e.table_name,
  e.column_name,
  'column absent'::text as detail
from expected_columns e
left join actual_columns a using (table_name, column_name)
where a.table_name is null
union all
select
  'extra_table'::text as issue,
  a.table_name,
  null::text as column_name,
  'table present but not in contract'::text as detail
from actual_tables a
left join expected_tables e using (table_name)
where e.table_name is null
union all
select
  'extra_column'::text as issue,
  a.table_name,
  a.column_name,
  'column present but not in contract'::text as detail
from actual_columns a
left join expected_columns e using (table_name, column_name)
where e.table_name is null
order by issue, table_name, column_name;
