// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DATABASE_URL        → pooler (port 6543) — used at runtime
    // DATABASE_URL_UNPOOLED → direct (port 5432) — used by `prisma migrate`
    // Prisma requires a direct connection for migrations; the pooler
    // (PgBouncer transaction mode) does not support multi-statement DDL.
    url: process.env["DATABASE_URL"],
    directUrl: process.env["DATABASE_URL_UNPOOLED"],
  },
});
