import type { Config } from "tailwindcss";

const config: Config = {
  theme: {
    extend: {
      colors: {
        "gv-primary": "var(--gv-primary)",
        "gv-primary-light": "var(--gv-primary-light)",
        "gv-aurora-cyan": "var(--gv-aurora-cyan)",
        "gv-aurora-emerald": "var(--gv-aurora-emerald)",
        "gv-aurora-rose": "var(--gv-aurora-rose)",
        "gv-aurora-amber": "var(--gv-aurora-amber)",
        "gv-aurora-indigo": "var(--gv-aurora-indigo)",
        "gv-bg-void": "var(--gv-bg-void)",
        "gv-bg-deep": "var(--gv-bg-deep)",
        "gv-bg-surface": "var(--gv-bg-surface)",
        "gv-bg-elevated": "var(--gv-bg-elevated)",
        "gv-text-primary": "var(--gv-text-primary)",
        "gv-text-secondary": "var(--gv-text-secondary)",
        "gv-text-muted": "var(--gv-text-muted)",
        "gv-text-accent": "var(--gv-text-accent)",
        gv: {
          primary: "var(--gv-primary)",
          "primary-light": "var(--gv-primary-light)",
          "primary-dark": "var(--gv-primary-dark)",
          "aurora-cyan": "var(--gv-aurora-cyan)",
          "aurora-emerald": "var(--gv-aurora-emerald)",
          "aurora-rose": "var(--gv-aurora-rose)",
          "aurora-amber": "var(--gv-aurora-amber)",
          "aurora-indigo": "var(--gv-aurora-indigo)",
          "bg-void": "var(--gv-bg-void)",
          "bg-deep": "var(--gv-bg-deep)",
          "bg-surface": "var(--gv-bg-surface)",
          "bg-elevated": "var(--gv-bg-elevated)",
          "bg-overlay": "var(--gv-bg-overlay)",
          "border-subtle": "var(--gv-border-subtle)",
          "border-active": "var(--gv-border-active)",
          "text-primary": "var(--gv-text-primary)",
          "text-secondary": "var(--gv-text-secondary)",
          "text-muted": "var(--gv-text-muted)",
          "text-accent": "var(--gv-text-accent)",
        },
      },
      fontFamily: {
        "gv-hero": ["Cabin Sketch", "sans-serif"],
        "gv-script": ["Manrope", "cursive"],
        body: ["Geist", "sans-serif"],
        "gv-display": ["var(--gv-font-display)"],
        "gv-body": ["var(--gv-font-body)"],
        "gv-ui": ["var(--gv-font-ui)"],
        "gv-mono": ["var(--gv-font-mono)"],
      },
      spacing: {
        "gv-1": "var(--gv-space-1)",
        "gv-2": "var(--gv-space-2)",
        "gv-3": "var(--gv-space-3)",
        "gv-4": "var(--gv-space-4)",
        "gv-6": "var(--gv-space-6)",
        "gv-8": "var(--gv-space-8)",
        "gv-12": "var(--gv-space-12)",
        "gv-16": "var(--gv-space-16)",
        "gv-24": "var(--gv-space-24)",
      },
      transitionDuration: {
        "gv-instant": "var(--gv-duration-instant)",
        "gv-fast": "var(--gv-duration-fast)",
        "gv-normal": "var(--gv-duration-normal)",
        "gv-slow": "var(--gv-duration-slow)",
        "gv-ambient": "var(--gv-duration-ambient)",
      },
      transitionTimingFunction: {
        "gv-out": "var(--gv-ease-out)",
        "gv-in": "var(--gv-ease-in)",
        "gv-spring": "var(--gv-ease-spring)",
      },
      borderRadius: {
        "gv-sm": "var(--gv-radius-sm)",
        "gv-md": "var(--gv-radius-md)",
        "gv-lg": "var(--gv-radius-lg)",
      },
    },
  },
};

export default config;
