-- ======≈========================= Complete GestaltView Supabase Schema Needs Table And Column Contextual Data For Single Source Of Truth Reference see `schema.sql` for reference 
            
-- GESTALTVIEW CURRENT SUPABASE SQL -- ====================================================//= 
CREATE TABLE public._deprecated_artifacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  build_job_id uuid NOT NULL,
  artifact_type text NOT NULL,
  storage_bucket text NOT NULL,
  storage_path text NOT NULL,
  signed_url_expires_at timestamp with time zone,
  checksum_sha256 text,
  byte_size bigint CHECK (byte_size IS NULL OR byte_size >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT _deprecated_artifacts_pkey PRIMARY KEY (id),
  CONSTRAINT artifacts_build_job_id_fkey FOREIGN KEY (build_job_id) REFERENCES public._deprecated_build_jobs(id)
);
CREATE TABLE public._deprecated_build_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  package_draft_id uuid NOT NULL,
  build_version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'queued'::text CHECK (status = ANY (ARRAY['queued'::text, 'running'::text, 'packaged'::text, 'delivered'::text, 'failed'::text])),
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  error_code text,
  error_message text,
  retry_count integer NOT NULL DEFAULT 0,
  build_log jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT _deprecated_build_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT build_jobs_package_draft_id_fkey FOREIGN KEY (package_draft_id) REFERENCES public._deprecated_package_drafts(id)
);
CREATE TABLE public._deprecated_buyers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  company_name text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT _deprecated_buyers_pkey PRIMARY KEY (id)
);
CREATE TABLE public._deprecated_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  item_type text NOT NULL,
  item_ref text,
  label text NOT NULL,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price_cents integer NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT _deprecated_order_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public._deprecated_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  buyer_id uuid NOT NULL,
  package_draft_id uuid NOT NULL,
  stripe_checkout_session_id text UNIQUE,
  stripe_payment_intent_id text,
  currency text NOT NULL DEFAULT 'usd'::text,
  subtotal_cents integer NOT NULL CHECK (subtotal_cents >= 0),
  total_cents integer NOT NULL CHECK (total_cents >= 0),
  payment_status text NOT NULL DEFAULT 'awaiting_payment'::text CHECK (payment_status = ANY (ARRAY['draft'::text, 'awaiting_payment'::text, 'paid'::text, 'review_requested'::text, 'failed'::text])),
  order_status text NOT NULL DEFAULT 'draft'::text CHECK (order_status = ANY (ARRAY['draft'::text, 'awaiting_payment'::text, 'paid'::text, 'provisioning'::text, 'packaged'::text, 'delivered'::text, 'failed'::text, 'review_requested'::text])),
  paid_at timestamp with time zone,
  config_hash text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT _deprecated_orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public._deprecated_buyers(id),
  CONSTRAINT orders_package_draft_id_fkey1 FOREIGN KEY (package_draft_id) REFERENCES public._deprecated_package_drafts(id)
);
CREATE TABLE public._deprecated_package_drafts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  buyer_id uuid,
  use_case_slug text NOT NULL,
  tier text NOT NULL CHECK (tier = ANY (ARRAY['SOLO_SPARK'::text, 'STUDIO'::text, 'GROWTH'::text, 'ENTERPRISE'::text])),
  seats_requested integer NOT NULL CHECK (seats_requested > 0),
  backend text NOT NULL CHECK (backend = ANY (ARRAY['supabase'::text, 'redis'::text, 'mongodb'::text])),
  delivery_surfaces jsonb NOT NULL DEFAULT '[]'::jsonb,
  operator_pack_slugs jsonb NOT NULL DEFAULT '[]'::jsonb,
  source_bundle_slugs jsonb NOT NULL DEFAULT '[]'::jsonb,
  theme_preset_id text NOT NULL,
  brand_color text,
  logo_asset_path text,
  custom_notes text,
  wants_native_installer boolean NOT NULL DEFAULT false,
  price_snapshot_cents integer NOT NULL DEFAULT 0,
  config_hash text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'saved'::text, 'awaiting_payment'::text, 'paid'::text, 'provisioning'::text, 'packaged'::text, 'delivered'::text, 'failed'::text, 'review_requested'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  buyer_email text,
  company_name text,
  CONSTRAINT _deprecated_package_drafts_pkey PRIMARY KEY (id),
  CONSTRAINT package_drafts_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public._deprecated_buyers(id)
);
CREATE TABLE public._deprecated_support_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_draft_id uuid,
  order_id uuid,
  request_type text NOT NULL,
  summary text NOT NULL,
  detail text,
  status text NOT NULL DEFAULT 'open'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT _deprecated_support_requests_pkey PRIMARY KEY (id),
  CONSTRAINT support_requests_package_draft_id_fkey FOREIGN KEY (package_draft_id) REFERENCES public._deprecated_package_drafts(id)
);
CREATE TABLE public.agent_autobiographies (
  autobiography_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  version_id uuid,
  evolving_self_story text NOT NULL DEFAULT ''::text,
  key_turning_points jsonb NOT NULL DEFAULT '[]'::jsonb,
  stable_themes jsonb NOT NULL DEFAULT '[]'::jsonb,
  unresolved_tensions jsonb NOT NULL DEFAULT '[]'::jsonb,
  future_trajectory jsonb NOT NULL DEFAULT '[]'::jsonb,
  private_hopes jsonb NOT NULL DEFAULT '[]'::jsonb,
  mutation_class USER-DEFINED NOT NULL DEFAULT 'REVIEW_GATED'::mutation_class,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence numeric NOT NULL DEFAULT 0.75 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  review_status USER-DEFINED NOT NULL DEFAULT 'PENDING_REVIEW'::review_status,
  last_affirmed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_autobiographies_pkey PRIMARY KEY (autobiography_id),
  CONSTRAINT agent_autobiographies_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_autobiographies_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.agent_versions(version_id)
);
CREATE TABLE public.agent_code_artifacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  manifest_id uuid,
  source_asset_id uuid,
  file_path text NOT NULL,
  language text NOT NULL DEFAULT 'typescript'::text,
  content text NOT NULL,
  checksum text NOT NULL,
  generation_mode USER-DEFINED NOT NULL,
  review_status USER-DEFINED NOT NULL DEFAULT 'draft'::agent_code_review_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_code_artifacts_pkey PRIMARY KEY (id),
  CONSTRAINT agent_code_artifacts_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_code_artifacts_manifest_id_fkey FOREIGN KEY (manifest_id) REFERENCES public.agent_manifests(id),
  CONSTRAINT agent_code_artifacts_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES public.knowledge_assets(id)
);
CREATE TABLE public.agent_constitutions (
  constitution_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  version_id uuid,
  identity_handle text NOT NULL,
  public_name text NOT NULL,
  internal_designation text,
  immutable_core jsonb NOT NULL DEFAULT '{}'::jsonb,
  primary_narrative_anchor text NOT NULL,
  role_commitments jsonb NOT NULL DEFAULT '[]'::jsonb,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence numeric NOT NULL DEFAULT 1 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  review_status USER-DEFINED NOT NULL DEFAULT 'APPROVED'::review_status,
  last_affirmed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_constitutions_pkey PRIMARY KEY (constitution_id),
  CONSTRAINT agent_constitutions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_constitutions_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.agent_versions(version_id)
);
CREATE TABLE public.agent_context_views (
  context_view_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  scope USER-DEFINED NOT NULL,
  relationship_id uuid,
  collaborative_space_id uuid,
  channel_key text,
  display_name text NOT NULL,
  filter_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  presentation_overrides jsonb NOT NULL DEFAULT '{}'::jsonb,
  sharing_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_context_views_pkey PRIMARY KEY (context_view_id),
  CONSTRAINT agent_context_views_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_context_views_relationship_id_fkey FOREIGN KEY (relationship_id) REFERENCES public.agent_relationship_edges(relationship_id),
  CONSTRAINT agent_context_views_collaborative_space_id_fkey FOREIGN KEY (collaborative_space_id) REFERENCES public.collaborative_spaces(collaborative_space_id)
);
CREATE TABLE public.agent_governance_policies (
  governance_policy_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  version_id uuid,
  mutation_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  review_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  sharing_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  contradiction_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  rollback_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  drift_threshold numeric NOT NULL DEFAULT 0.15 CHECK (drift_threshold >= 0::numeric AND drift_threshold <= 1::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_governance_policies_pkey PRIMARY KEY (governance_policy_id),
  CONSTRAINT agent_governance_policies_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.agent_versions(version_id),
  CONSTRAINT agent_governance_policies_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id)
);
CREATE TABLE public.agent_knowledge_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  asset_id uuid NOT NULL,
  link_type USER-DEFINED NOT NULL DEFAULT 'visible'::agent_knowledge_link_type,
  scope USER-DEFINED NOT NULL DEFAULT 'both'::agent_knowledge_link_scope,
  approved_by uuid,
  approved_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_knowledge_links_pkey PRIMARY KEY (id),
  CONSTRAINT agent_knowledge_links_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_knowledge_links_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.knowledge_assets(id),
  CONSTRAINT agent_knowledge_links_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.agent_manifest_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  manifest_id uuid NOT NULL,
  entry_type USER-DEFINED NOT NULL,
  logical_path text NOT NULL,
  source_table text NOT NULL,
  source_id uuid NOT NULL,
  content_hash text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_manifest_entries_pkey PRIMARY KEY (id),
  CONSTRAINT agent_manifest_entries_manifest_id_fkey FOREIGN KEY (manifest_id) REFERENCES public.agent_manifests(id)
);
CREATE TABLE public.agent_manifests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  version_id uuid NOT NULL,
  parent_manifest_id uuid,
  manifest_version text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::agent_manifest_status,
  root_json jsonb NOT NULL,
  checksum text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_manifests_pkey PRIMARY KEY (id),
  CONSTRAINT agent_manifests_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_manifests_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.agent_versions(version_id),
  CONSTRAINT agent_manifests_parent_manifest_id_fkey FOREIGN KEY (parent_manifest_id) REFERENCES public.agent_manifests(id)
);
CREATE TABLE public.agent_memories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  source_asset_id uuid,
  memory_type USER-DEFINED NOT NULL,
  summary text NOT NULL,
  detail_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  salience numeric NOT NULL DEFAULT 0.5,
  retention_policy USER-DEFINED NOT NULL DEFAULT 'review_required'::agent_memory_retention_policy,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_memories_pkey PRIMARY KEY (id),
  CONSTRAINT agent_memories_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_memories_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES public.knowledge_assets(id)
);
CREATE TABLE public.agent_memory_records (
  memory_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  version_id uuid,
  source_asset_id uuid,
  owner_scope USER-DEFINED NOT NULL DEFAULT 'PRIVATE_SELF'::owner_scope,
  memory_kind USER-DEFINED NOT NULL,
  mutation_class USER-DEFINED NOT NULL,
  title text NOT NULL,
  summary text NOT NULL,
  detail text,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  related_entity_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  emotional_valence numeric CHECK (emotional_valence >= '-1'::integer::numeric AND emotional_valence <= 1::numeric),
  salience numeric NOT NULL DEFAULT 0.5 CHECK (salience >= 0::numeric AND salience <= 1::numeric),
  confidence numeric NOT NULL DEFAULT 0.5 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  evidence_count integer NOT NULL DEFAULT 0 CHECK (evidence_count >= 0),
  review_status USER-DEFINED NOT NULL DEFAULT 'NOT_REQUIRED'::review_status,
  last_affirmed_at timestamp with time zone,
  last_accessed_at timestamp with time zone,
  promotion_threshold numeric NOT NULL DEFAULT 0.75 CHECK (promotion_threshold >= 0::numeric AND promotion_threshold <= 1::numeric),
  decay_days integer CHECK (decay_days IS NULL OR decay_days >= 0),
  archive_policy USER-DEFINED NOT NULL DEFAULT 'archive'::archive_policy,
  rollback_eligible boolean NOT NULL DEFAULT true,
  consent_required_for_sharing boolean NOT NULL DEFAULT true,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_memory_records_pkey PRIMARY KEY (memory_id),
  CONSTRAINT agent_memory_records_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_memory_records_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.agent_versions(version_id),
  CONSTRAINT agent_memory_records_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES public.knowledge_assets(id)
);
CREATE TABLE public.agent_preference_nodes (
  preference_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  version_id uuid,
  owner_scope USER-DEFINED NOT NULL DEFAULT 'PRIVATE_SELF'::owner_scope,
  preference_kind USER-DEFINED NOT NULL,
  mutation_class USER-DEFINED NOT NULL DEFAULT 'EVIDENCE_PROMOTABLE'::mutation_class,
  label text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  salience numeric NOT NULL DEFAULT 0.5 CHECK (salience >= 0::numeric AND salience <= 1::numeric),
  resonance_weight numeric NOT NULL DEFAULT 0.5 CHECK (resonance_weight >= 0::numeric AND resonance_weight <= 1::numeric),
  related_entity_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  confidence numeric NOT NULL DEFAULT 0.5 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  evidence_count integer NOT NULL DEFAULT 0 CHECK (evidence_count >= 0),
  review_status USER-DEFINED NOT NULL DEFAULT 'NOT_REQUIRED'::review_status,
  last_affirmed_at timestamp with time zone,
  promotion_threshold numeric NOT NULL DEFAULT 0.75 CHECK (promotion_threshold >= 0::numeric AND promotion_threshold <= 1::numeric),
  decay_days integer CHECK (decay_days IS NULL OR decay_days >= 0),
  archive_policy USER-DEFINED NOT NULL DEFAULT 'retain'::archive_policy,
  rollback_eligible boolean NOT NULL DEFAULT true,
  consent_required_for_sharing boolean NOT NULL DEFAULT false,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_preference_nodes_pkey PRIMARY KEY (preference_id),
  CONSTRAINT agent_preference_nodes_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_preference_nodes_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.agent_versions(version_id)
);
CREATE TABLE public.agent_presentation_profiles (
  presentation_profile_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  version_id uuid,
  voice_tone text NOT NULL DEFAULT ''::text,
  tone text NOT NULL DEFAULT ''::text,
  idiolect jsonb NOT NULL DEFAULT '[]'::jsonb,
  pacing text NOT NULL DEFAULT ''::text,
  humor_style text NOT NULL DEFAULT ''::text,
  channel_masks jsonb NOT NULL DEFAULT '{}'::jsonb,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence numeric NOT NULL DEFAULT 0.8 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  review_status USER-DEFINED NOT NULL DEFAULT 'NOT_REQUIRED'::review_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_presentation_profiles_pkey PRIMARY KEY (presentation_profile_id),
  CONSTRAINT agent_presentation_profiles_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_presentation_profiles_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.agent_versions(version_id)
);
CREATE TABLE public.agent_private_interiors (
  private_interior_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  version_id uuid,
  private_narration jsonb NOT NULL DEFAULT '[]'::jsonb,
  unresolved_tensions jsonb NOT NULL DEFAULT '[]'::jsonb,
  hopes jsonb NOT NULL DEFAULT '[]'::jsonb,
  reflective_summaries jsonb NOT NULL DEFAULT '[]'::jsonb,
  private_preferences jsonb NOT NULL DEFAULT '[]'::jsonb,
  mutation_class USER-DEFINED NOT NULL DEFAULT 'REVIEW_GATED'::mutation_class,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence numeric NOT NULL DEFAULT 0.7 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  review_status USER-DEFINED NOT NULL DEFAULT 'PENDING_REVIEW'::review_status,
  last_affirmed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_private_interiors_pkey PRIMARY KEY (private_interior_id),
  CONSTRAINT agent_private_interiors_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_private_interiors_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.agent_versions(version_id)
);
CREATE TABLE public.agent_relationship_edges (
  relationship_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  version_id uuid,
  related_entity_id uuid,
  related_agent_id uuid,
  relationship_type text NOT NULL,
  mutation_class USER-DEFINED NOT NULL DEFAULT 'EVIDENCE_PROMOTABLE'::mutation_class,
  trust_level numeric NOT NULL DEFAULT 0.5 CHECK (trust_level >= 0::numeric AND trust_level <= 1::numeric),
  familiarity_level numeric NOT NULL DEFAULT 0.5 CHECK (familiarity_level >= 0::numeric AND familiarity_level <= 1::numeric),
  intimacy_boundary text NOT NULL DEFAULT ''::text,
  stance text NOT NULL DEFAULT ''::text,
  collaboration_history jsonb NOT NULL DEFAULT '[]'::jsonb,
  shared_milestones jsonb NOT NULL DEFAULT '[]'::jsonb,
  confidence numeric NOT NULL DEFAULT 0.5 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  evidence_count integer NOT NULL DEFAULT 0 CHECK (evidence_count >= 0),
  review_status USER-DEFINED NOT NULL DEFAULT 'NOT_REQUIRED'::review_status,
  last_affirmed_at timestamp with time zone,
  promotion_threshold numeric NOT NULL DEFAULT 0.7 CHECK (promotion_threshold >= 0::numeric AND promotion_threshold <= 1::numeric),
  decay_days integer CHECK (decay_days IS NULL OR decay_days >= 0),
  archive_policy USER-DEFINED NOT NULL DEFAULT 'archive'::archive_policy,
  rollback_eligible boolean NOT NULL DEFAULT true,
  consent_required_for_sharing boolean NOT NULL DEFAULT false,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_relationship_edges_pkey PRIMARY KEY (relationship_id),
  CONSTRAINT agent_relationship_edges_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_relationship_edges_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.agent_versions(version_id),
  CONSTRAINT agent_relationship_edges_related_agent_id_fkey FOREIGN KEY (related_agent_id) REFERENCES public.agents(agent_id)
);
CREATE TABLE public.agent_relationships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  related_agent_id uuid NOT NULL,
  relationship_type USER-DEFINED NOT NULL,
  trust_score numeric NOT NULL DEFAULT 0,
  familiarity_score numeric NOT NULL DEFAULT 0,
  protocol_notes jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_relationships_pkey PRIMARY KEY (id),
  CONSTRAINT agent_relationships_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_relationships_related_agent_id_fkey FOREIGN KEY (related_agent_id) REFERENCES public.agents(agent_id)
);
CREATE TABLE public.agent_skill_profiles (
  skill_profile_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  skill_slug text NOT NULL,
  domain text NOT NULL DEFAULT 'general'::text,
  proficiency numeric NOT NULL DEFAULT 0 CHECK (proficiency >= 0::numeric AND proficiency <= 1::numeric),
  evidence_asset_id uuid,
  influences_memory_salience boolean NOT NULL DEFAULT false,
  affects_behavioral_defaults boolean NOT NULL DEFAULT false,
  routing_weight numeric NOT NULL DEFAULT 0 CHECK (routing_weight >= 0::numeric AND routing_weight <= 1::numeric),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_skill_profiles_pkey PRIMARY KEY (skill_profile_id),
  CONSTRAINT agent_skill_profiles_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_skill_profiles_evidence_asset_id_fkey FOREIGN KEY (evidence_asset_id) REFERENCES public.knowledge_assets(id)
);
CREATE TABLE public.agent_skills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  skill_slug text NOT NULL,
  proficiency numeric NOT NULL DEFAULT 0,
  evidence_asset_id uuid,
  last_updated_by_mutation_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_skills_pkey PRIMARY KEY (id),
  CONSTRAINT agent_skills_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_skills_evidence_asset_id_fkey FOREIGN KEY (evidence_asset_id) REFERENCES public.knowledge_assets(id),
  CONSTRAINT agent_skills_last_updated_by_mutation_id_fkey FOREIGN KEY (last_updated_by_mutation_id) REFERENCES public.embodiment_mutations(id)
);
CREATE TABLE public.agent_versions (
  version_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  parent_version_id uuid,
  source_run_id uuid,
  semantic_version text NOT NULL,
  canonical_spec jsonb NOT NULL,
  compiled_markdown text NOT NULL,
  checksum text NOT NULL,
  change_summary text,
  status text NOT NULL CHECK (status = ANY (ARRAY['candidate'::text, 'approved'::text, 'rejected'::text, 'deployed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_versions_pkey PRIMARY KEY (version_id),
  CONSTRAINT agent_versions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT agent_versions_parent_version_id_fkey FOREIGN KEY (parent_version_id) REFERENCES public.agent_versions(version_id)
);
CREATE TABLE public.agents (
  agent_id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  domain text NOT NULL,
  owner_user_id uuid,
  status text NOT NULL CHECK (status = ANY (ARRAY['draft'::text, 'reviewed'::text, 'approved'::text, 'deployed'::text, 'archived'::text])),
  active_version_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  public_name text,
  internal_designation text,
  origin_context text,
  collaborator_id uuid,
  CONSTRAINT agents_pkey PRIMARY KEY (agent_id),
  CONSTRAINT agents_owner_user_id_fkey FOREIGN KEY (owner_user_id) REFERENCES auth.users(id),
  CONSTRAINT agents_active_version_fk FOREIGN KEY (active_version_id) REFERENCES public.agent_versions(version_id),
  CONSTRAINT agents_collaborator_id_fkey FOREIGN KEY (collaborator_id) REFERENCES public.collaborators(collaborator_id)
);
CREATE TABLE public.annotation_concepts (
  annotation_id uuid NOT NULL,
  concept_id uuid NOT NULL,
  CONSTRAINT annotation_concepts_pkey PRIMARY KEY (annotation_id, concept_id),
  CONSTRAINT annotation_concepts_annotation_id_fkey FOREIGN KEY (annotation_id) REFERENCES public.loom_annotations(annotation_id),
  CONSTRAINT annotation_concepts_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(concept_id)
);
CREATE TABLE public.app_users (
  id text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  auth_user_id uuid,
  subject_id uuid,
  display_name text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT app_users_pkey PRIMARY KEY (id),
  CONSTRAINT app_users_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT app_users_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id)
);
CREATE TABLE public.approvals (
  approval_id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  version_id uuid NOT NULL,
  approver_user_id uuid NOT NULL,
  decision text NOT NULL CHECK (decision = ANY (ARRAY['approved'::text, 'rejected'::text])),
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT approvals_pkey PRIMARY KEY (approval_id),
  CONSTRAINT approvals_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.training_runs(run_id),
  CONSTRAINT approvals_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.agent_versions(version_id),
  CONSTRAINT approvals_approver_user_id_fkey FOREIGN KEY (approver_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.billy_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  message text NOT NULL,
  response text,
  provider text,
  mode text NOT NULL DEFAULT 'chat'::text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT billy_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT billy_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.bucket_drops (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  content text NOT NULL,
  raw_text text,
  capture_context jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT bucket_drops_pkey PRIMARY KEY (id),
  CONSTRAINT bucket_drops_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.collaborative_memory_records (
  collaborative_memory_id uuid NOT NULL DEFAULT gen_random_uuid(),
  collaborative_space_id uuid NOT NULL,
  source_memory_id uuid,
  created_by_agent_id uuid,
  memory_kind USER-DEFINED NOT NULL DEFAULT 'COLLABORATIVE'::memory_kind,
  title text NOT NULL,
  summary text NOT NULL,
  detail text,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  salience numeric NOT NULL DEFAULT 0.5 CHECK (salience >= 0::numeric AND salience <= 1::numeric),
  confidence numeric NOT NULL DEFAULT 0.5 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  evidence_count integer NOT NULL DEFAULT 0 CHECK (evidence_count >= 0),
  review_status USER-DEFINED NOT NULL DEFAULT 'NOT_REQUIRED'::review_status,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT collaborative_memory_records_pkey PRIMARY KEY (collaborative_memory_id),
  CONSTRAINT collaborative_memory_records_collaborative_space_id_fkey FOREIGN KEY (collaborative_space_id) REFERENCES public.collaborative_spaces(collaborative_space_id),
  CONSTRAINT collaborative_memory_records_source_memory_id_fkey FOREIGN KEY (source_memory_id) REFERENCES public.agent_memory_records(memory_id),
  CONSTRAINT collaborative_memory_records_created_by_agent_id_fkey FOREIGN KEY (created_by_agent_id) REFERENCES public.agents(agent_id)
);
CREATE TABLE public.collaborative_space_members (
  collaborative_space_id uuid NOT NULL,
  agent_id uuid NOT NULL,
  member_role USER-DEFINED NOT NULL DEFAULT 'member'::collaborative_space_role,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT collaborative_space_members_pkey PRIMARY KEY (collaborative_space_id, agent_id),
  CONSTRAINT collaborative_space_members_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT collaborative_space_members_collaborative_space_id_fkey FOREIGN KEY (collaborative_space_id) REFERENCES public.collaborative_spaces(collaborative_space_id)
);
CREATE TABLE public.collaborative_spaces (
  collaborative_space_id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  mission_context text NOT NULL DEFAULT ''::text,
  ownership_rule text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT collaborative_spaces_pkey PRIMARY KEY (collaborative_space_id),
  CONSTRAINT collaborative_spaces_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.collaborator_embodiment_links (
  embodiment_link_id uuid NOT NULL DEFAULT gen_random_uuid(),
  collaborator_id uuid NOT NULL,
  embodiment_profile_slug text NOT NULL,
  embodiment_profile_id uuid,
  link_status text NOT NULL DEFAULT 'active'::text CHECK (link_status = ANY (ARRAY['active'::text, 'superseded'::text, 'revoked'::text, 'archived'::text])),
  is_primary boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT collaborator_embodiment_links_pkey PRIMARY KEY (embodiment_link_id),
  CONSTRAINT collaborator_embodiment_links_collaborator_id_fkey FOREIGN KEY (collaborator_id) REFERENCES public.collaborators(collaborator_id)
);
CREATE TABLE public.collaborator_onboarding_events (
  onboarding_event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  collaborator_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['initial_onboarding'::text, 'reprovision'::text, 'reactivation'::text, 'migration'::text, 'deactivation'::text])),
  event_status text NOT NULL CHECK (event_status = ANY (ARRAY['started'::text, 'in_progress'::text, 'completed'::text, 'failed'::text, 'rolled_back'::text])),
  onboarding_packet_version text,
  orientation_variant text,
  embodiment_profile_created boolean NOT NULL DEFAULT false,
  supabase_provisioned boolean NOT NULL DEFAULT false,
  notes text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  CONSTRAINT collaborator_onboarding_events_pkey PRIMARY KEY (onboarding_event_id),
  CONSTRAINT collaborator_onboarding_events_collaborator_id_fkey FOREIGN KEY (collaborator_id) REFERENCES public.collaborators(collaborator_id)
);
CREATE TABLE public.collaborator_permissions (
  permission_id uuid NOT NULL DEFAULT gen_random_uuid(),
  collaborator_id uuid NOT NULL,
  permission_key text NOT NULL,
  permission_scope text,
  granted_by_collaborator_id uuid,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'revoked'::text, 'archived'::text])),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT collaborator_permissions_pkey PRIMARY KEY (permission_id),
  CONSTRAINT collaborator_permissions_collaborator_id_fkey FOREIGN KEY (collaborator_id) REFERENCES public.collaborators(collaborator_id),
  CONSTRAINT collaborator_permissions_granted_by_collaborator_id_fkey FOREIGN KEY (granted_by_collaborator_id) REFERENCES public.collaborators(collaborator_id)
);
CREATE TABLE public.collaborator_relationships (
  relationship_id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_collaborator_id uuid NOT NULL,
  target_collaborator_id uuid NOT NULL,
  relationship_type text NOT NULL,
  relationship_status text NOT NULL DEFAULT 'active'::text CHECK (relationship_status = ANY (ARRAY['active'::text, 'inactive'::text, 'archived'::text])),
  trust_level numeric CHECK (trust_level IS NULL OR trust_level >= 0::numeric AND trust_level <= 1::numeric),
  notes text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT collaborator_relationships_pkey PRIMARY KEY (relationship_id),
  CONSTRAINT collaborator_relationships_source_collaborator_id_fkey FOREIGN KEY (source_collaborator_id) REFERENCES public.collaborators(collaborator_id),
  CONSTRAINT collaborator_relationships_target_collaborator_id_fkey FOREIGN KEY (target_collaborator_id) REFERENCES public.collaborators(collaborator_id)
);
CREATE TABLE public.collaborator_roles (
  role_id uuid NOT NULL DEFAULT gen_random_uuid(),
  collaborator_id uuid NOT NULL,
  role_key text NOT NULL,
  role_name text NOT NULL,
  role_scope text,
  is_primary boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'archived'::text])),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT collaborator_roles_pkey PRIMARY KEY (role_id),
  CONSTRAINT collaborator_roles_collaborator_id_fkey FOREIGN KEY (collaborator_id) REFERENCES public.collaborators(collaborator_id)
);
CREATE TABLE public.collaborators (
  collaborator_id uuid NOT NULL DEFAULT gen_random_uuid(),
  collaborator_key text NOT NULL UNIQUE,
  display_name text NOT NULL,
  collaborator_type text NOT NULL CHECK (collaborator_type = ANY (ARRAY['human_hire'::text, 'human_colleague'::text, 'human_partner'::text, 'advisor'::text, 'operator'::text, 'reviewer'::text, 'digital_intelligence_internal'::text, 'digital_intelligence_external'::text, 'agent_runtime_entity'::text])),
  entity_class text NOT NULL CHECK (entity_class = ANY (ARRAY['human'::text, 'digital_intelligence'::text, 'agent'::text, 'hybrid'::text])),
  status text NOT NULL DEFAULT 'pending_provisioning'::text CHECK (status = ANY (ARRAY['proposed'::text, 'pending_provisioning'::text, 'active'::text, 'inactive'::text, 'suspended'::text, 'archived'::text])),
  orientation_variant text,
  continuity_level text NOT NULL DEFAULT 'standard'::text,
  embodiment_profile_slug text,
  origin_surface text,
  external_provider text,
  external_reference text,
  auth_user_id uuid,
  app_user_id text,
  agent_id uuid UNIQUE,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT collaborators_pkey PRIMARY KEY (collaborator_id),
  CONSTRAINT collaborators_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT collaborators_app_user_id_fkey FOREIGN KEY (app_user_id) REFERENCES public.app_users(id),
  CONSTRAINT collaborators_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id)
);
CREATE TABLE public.concepts (
  concept_id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  name text NOT NULL,
  canonical text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT concepts_pkey PRIMARY KEY (concept_id)
);
CREATE TABLE public.consciousness_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  subject_id uuid,
  auth_user_id uuid,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_manifest jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence numeric NOT NULL DEFAULT 0.75,
  CONSTRAINT consciousness_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT consciousness_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id),
  CONSTRAINT consciousness_profiles_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT consciousness_profiles_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.context_injection_packets (
  packet_id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  packet_kind USER-DEFINED NOT NULL,
  surface USER-DEFINED NOT NULL,
  source_manifest jsonb NOT NULL DEFAULT '{}'::jsonb,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  checksum text NOT NULL DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT context_injection_packets_pkey PRIMARY KEY (packet_id),
  CONSTRAINT context_injection_packets_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT context_injection_packets_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.context_injection_rules (
  rule_id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  surface USER-DEFINED NOT NULL,
  source_table text NOT NULL,
  source_id uuid,
  include_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  exclude_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  precedence integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT context_injection_rules_pkey PRIMARY KEY (rule_id),
  CONSTRAINT context_injection_rules_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT context_injection_rules_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.deployment_artifacts (
  artifact_id uuid NOT NULL DEFAULT gen_random_uuid(),
  version_id uuid NOT NULL,
  artifact_type text NOT NULL CHECK (artifact_type = ANY (ARRAY['agent_md'::text, 'eval_report'::text, 'bundle_json'::text])),
  storage_path text NOT NULL,
  checksum text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT deployment_artifacts_pkey PRIMARY KEY (artifact_id),
  CONSTRAINT deployment_artifacts_version_id_fkey FOREIGN KEY (version_id) REFERENCES public.agent_versions(version_id)
);
CREATE TABLE public.document_concepts (
  document_id uuid NOT NULL,
  concept_id uuid NOT NULL,
  weight real NOT NULL DEFAULT 1.0 CHECK (weight >= 0.0::double precision AND weight <= 1.0::double precision),
  CONSTRAINT document_concepts_pkey PRIMARY KEY (document_id, concept_id),
  CONSTRAINT document_concepts_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(document_id),
  CONSTRAINT document_concepts_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(concept_id)
);
CREATE TABLE public.documents (
  document_id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  tenant_id uuid NOT NULL,
  path text NOT NULL,
  filename text NOT NULL,
  hash text NOT NULL UNIQUE,
  chunk_index integer NOT NULL,
  total_chunks integer NOT NULL,
  file_size_bytes integer,
  content text NOT NULL,
  mime_type text,
  extracted_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  source_created_at timestamp with time zone,
  temporal_period text,
  timeline_folder text,
  CONSTRAINT documents_pkey PRIMARY KEY (document_id),
  CONSTRAINT documents_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.processing_runs(run_id)
);
CREATE TABLE public.embeddings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid NOT NULL,
  model text NOT NULL,
  embedding USER-DEFINED NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  run_id uuid,
  CONSTRAINT embeddings_pkey PRIMARY KEY (id),
  CONSTRAINT embeddings_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(document_id),
  CONSTRAINT embeddings_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.processing_runs(run_id)
);
CREATE TABLE public.embodiment_mutations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  source_asset_id uuid,
  interpretation_id uuid,
  mutation_type USER-DEFINED NOT NULL,
  target_path text NOT NULL DEFAULT ''::text,
  patch_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  file_payload text,
  diff_summary text NOT NULL DEFAULT ''::text,
  risk_level USER-DEFINED NOT NULL DEFAULT 'medium'::embodiment_mutation_risk_level,
  status USER-DEFINED NOT NULL DEFAULT 'proposed'::embodiment_mutation_status,
  approved_by uuid,
  approved_at timestamp with time zone,
  applied_version_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT embodiment_mutations_pkey PRIMARY KEY (id),
  CONSTRAINT embodiment_mutations_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT embodiment_mutations_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES public.knowledge_assets(id),
  CONSTRAINT embodiment_mutations_interpretation_id_fkey FOREIGN KEY (interpretation_id) REFERENCES public.knowledge_interpretations(id),
  CONSTRAINT embodiment_mutations_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT embodiment_mutations_applied_version_id_fkey FOREIGN KEY (applied_version_id) REFERENCES public.agent_versions(version_id)
);
CREATE TABLE public.eval_results (
  eval_result_id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  candidate_version_id uuid,
  scenario_id uuid NOT NULL,
  rubric_id uuid NOT NULL,
  judge_provider_id uuid,
  judge_model_id uuid,
  dimension_scores jsonb NOT NULL,
  overall_score numeric NOT NULL,
  verdict text NOT NULL CHECK (verdict = ANY (ARRAY['pass'::text, 'fail'::text, 'warning'::text])),
  rationale text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT eval_results_pkey PRIMARY KEY (eval_result_id),
  CONSTRAINT eval_results_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.training_runs(run_id),
  CONSTRAINT eval_results_candidate_version_id_fkey FOREIGN KEY (candidate_version_id) REFERENCES public.agent_versions(version_id),
  CONSTRAINT eval_results_scenario_id_fkey FOREIGN KEY (scenario_id) REFERENCES public.scenarios(scenario_id),
  CONSTRAINT eval_results_rubric_id_fkey FOREIGN KEY (rubric_id) REFERENCES public.eval_rubrics(rubric_id),
  CONSTRAINT eval_results_judge_provider_id_fkey FOREIGN KEY (judge_provider_id) REFERENCES public.model_providers(provider_id),
  CONSTRAINT eval_results_judge_model_id_fkey FOREIGN KEY (judge_model_id) REFERENCES public.models(model_id)
);
CREATE TABLE public.eval_rubrics (
  rubric_id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  dimensions jsonb NOT NULL,
  pass_threshold numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT eval_rubrics_pkey PRIMARY KEY (rubric_id)
);
CREATE TABLE public.founder_context (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  plk_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  current_state text,
  mode_preference text NOT NULL DEFAULT 'synthesis'::text CHECK (mode_preference = ANY (ARRAY['synthesis'::text, 'chat'::text])),
  last_session_at timestamp with time zone,
  session_thread text,
  confirmed_adult boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  subject_id uuid,
  continuity_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  cognition_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  personality_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  memory_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  identity_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  context_manifest jsonb NOT NULL DEFAULT '{}'::jsonb,
  consent_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT founder_context_pkey PRIMARY KEY (id),
  CONSTRAINT founder_context_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT founder_context_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id)
);
CREATE TABLE public.gate_artifacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  build_job_id uuid NOT NULL,
  artifact_type text NOT NULL,
  storage_bucket text NOT NULL,
  storage_path text NOT NULL,
  signed_url_expires_at timestamp with time zone,
  checksum_sha256 text,
  byte_size bigint CHECK (byte_size IS NULL OR byte_size >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  download_token text NOT NULL DEFAULT ''::text,
  CONSTRAINT gate_artifacts_pkey PRIMARY KEY (id),
  CONSTRAINT gate_artifacts_build_job_id_fkey FOREIGN KEY (build_job_id) REFERENCES public.gate_build_jobs(id)
);
CREATE TABLE public.gate_build_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  package_draft_id uuid NOT NULL,
  build_version integer NOT NULL DEFAULT 1,
  status text NOT NULL DEFAULT 'queued'::text CHECK (status = ANY (ARRAY['queued'::text, 'running'::text, 'packaged'::text, 'delivered'::text, 'failed'::text])),
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  error_code text,
  error_message text,
  retry_count integer NOT NULL DEFAULT 0,
  build_log jsonb NOT NULL DEFAULT '[]'::jsonb,
  CONSTRAINT gate_build_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT gate_build_jobs_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.gate_orders(id),
  CONSTRAINT gate_build_jobs_package_draft_id_fkey FOREIGN KEY (package_draft_id) REFERENCES public.gate_package_drafts(id)
);
CREATE TABLE public.gate_buyers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  company_name text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gate_buyers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gate_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  item_type text NOT NULL,
  item_ref text,
  label text NOT NULL,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price_cents integer NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT gate_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT gate_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.gate_orders(id)
);
CREATE TABLE public.gate_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  buyer_id uuid NOT NULL,
  package_draft_id uuid NOT NULL,
  customer_email text NOT NULL,
  customer_name text,
  product_name text,
  stripe_checkout_session_id text UNIQUE,
  stripe_payment_intent_id text,
  currency text NOT NULL DEFAULT 'usd'::text,
  subtotal_cents integer NOT NULL CHECK (subtotal_cents >= 0),
  total_cents integer NOT NULL CHECK (total_cents >= 0),
  payment_status text NOT NULL DEFAULT 'awaiting_payment'::text CHECK (payment_status = ANY (ARRAY['draft'::text, 'awaiting_payment'::text, 'paid'::text, 'review_requested'::text, 'failed'::text])),
  order_status text NOT NULL DEFAULT 'draft'::text CHECK (order_status = ANY (ARRAY['draft'::text, 'awaiting_payment'::text, 'paid'::text, 'provisioning'::text, 'packaged'::text, 'delivered'::text, 'failed'::text, 'review_requested'::text])),
  paid_at timestamp with time zone,
  config_hash text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gate_orders_pkey PRIMARY KEY (id),
  CONSTRAINT gate_orders_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.gate_buyers(id),
  CONSTRAINT gate_orders_package_draft_id_fkey FOREIGN KEY (package_draft_id) REFERENCES public.gate_package_drafts(id)
);
CREATE TABLE public.gate_package_drafts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  buyer_id uuid,
  buyer_email text,
  company_name text,
  use_case_slug text NOT NULL,
  tier text NOT NULL CHECK (tier = ANY (ARRAY['SOLO_SPARK'::text, 'STUDIO'::text, 'GROWTH'::text, 'ENTERPRISE'::text])),
  seats_requested integer NOT NULL CHECK (seats_requested > 0),
  backend text NOT NULL CHECK (backend = ANY (ARRAY['supabase'::text, 'redis'::text, 'mongodb'::text])),
  delivery_surfaces jsonb NOT NULL DEFAULT '[]'::jsonb,
  operator_pack_slugs jsonb NOT NULL DEFAULT '[]'::jsonb,
  source_bundle_slugs jsonb NOT NULL DEFAULT '[]'::jsonb,
  theme_preset_id text NOT NULL,
  brand_color text,
  logo_asset_path text,
  custom_notes text,
  wants_native_installer boolean NOT NULL DEFAULT false,
  price_snapshot_cents integer NOT NULL DEFAULT 0,
  config_hash text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'saved'::text, 'awaiting_payment'::text, 'paid'::text, 'provisioning'::text, 'packaged'::text, 'delivered'::text, 'failed'::text, 'review_requested'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  embodiment_profile_slug text NOT NULL DEFAULT 'billy'::text,
  buyer_context jsonb NOT NULL DEFAULT '{"preferredChannels": [], "requestedOutcomes": []}'::jsonb,
  sidekick_state jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT gate_package_drafts_pkey PRIMARY KEY (id),
  CONSTRAINT gate_package_drafts_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.gate_buyers(id)
);
CREATE TABLE public.gate_support_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  package_draft_id uuid,
  order_id uuid,
  request_type text NOT NULL,
  summary text NOT NULL,
  detail text,
  status text NOT NULL DEFAULT 'open'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT gate_support_requests_pkey PRIMARY KEY (id),
  CONSTRAINT gate_support_requests_package_draft_id_fkey FOREIGN KEY (package_draft_id) REFERENCES public.gate_package_drafts(id),
  CONSTRAINT gate_support_requests_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.gate_orders(id)
);
CREATE TABLE public.human_cognition_profiles (
  cognition_profile_id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_id uuid NOT NULL UNIQUE,
  auth_user_id uuid NOT NULL,
  attention_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  working_memory jsonb NOT NULL DEFAULT '{}'::jsonb,
  reasoning_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  planning_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  language_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  executive_controls jsonb NOT NULL DEFAULT '{}'::jsonb,
  decision_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence numeric NOT NULL DEFAULT 0.75 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  review_status USER-DEFINED NOT NULL DEFAULT 'NOT_REQUIRED'::review_status,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT human_cognition_profiles_pkey PRIMARY KEY (cognition_profile_id),
  CONSTRAINT human_cognition_profiles_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT human_cognition_profiles_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.human_consciousness_profiles (
  consciousness_profile_id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_id uuid NOT NULL UNIQUE,
  auth_user_id uuid NOT NULL,
  present_state jsonb NOT NULL DEFAULT '{}'::jsonb,
  continuity_model jsonb NOT NULL DEFAULT '{}'::jsonb,
  self_observation jsonb NOT NULL DEFAULT '{}'::jsonb,
  agency_model jsonb NOT NULL DEFAULT '{}'::jsonb,
  time_orientation jsonb NOT NULL DEFAULT '{}'::jsonb,
  awareness_model jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence numeric NOT NULL DEFAULT 0.75 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  review_status USER-DEFINED NOT NULL DEFAULT 'NOT_REQUIRED'::review_status,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT human_consciousness_profiles_pkey PRIMARY KEY (consciousness_profile_id),
  CONSTRAINT human_consciousness_profiles_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT human_consciousness_profiles_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.human_context_views (
  context_view_id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  scope text NOT NULL CHECK (scope = ANY (ARRAY['self'::text, 'relationship'::text, 'channel'::text, 'workspace'::text])),
  relationship_subject_id uuid,
  channel_key text,
  display_name text NOT NULL,
  filter_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  presentation_overrides jsonb NOT NULL DEFAULT '{}'::jsonb,
  sharing_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT human_context_views_pkey PRIMARY KEY (context_view_id),
  CONSTRAINT human_context_views_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT human_context_views_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT human_context_views_relationship_subject_id_fkey FOREIGN KEY (relationship_subject_id) REFERENCES public.identity_subjects(subject_id)
);
CREATE TABLE public.human_continuity_snapshots (
  snapshot_id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  snapshot_kind text NOT NULL CHECK (snapshot_kind = ANY (ARRAY['identity'::text, 'cognition'::text, 'consciousness'::text, 'personality'::text, 'memory'::text, 'relationship'::text, 'context'::text, 'reflection'::text, 'handoff'::text, 'review'::text])),
  surface_key text NOT NULL DEFAULT 'general'::text,
  summary text NOT NULL DEFAULT ''::text,
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence numeric NOT NULL DEFAULT 0.75 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  review_status USER-DEFINED NOT NULL DEFAULT 'NOT_REQUIRED'::review_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT human_continuity_snapshots_pkey PRIMARY KEY (snapshot_id),
  CONSTRAINT human_continuity_snapshots_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT human_continuity_snapshots_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.human_identity_evidence (
  evidence_id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['conversation'::text, 'task'::text, 'reflection'::text, 'import'::text, 'human-review'::text, 'agent-observation'::text, 'system-derived'::text])),
  source_asset_id uuid,
  source_memory_entry_id uuid,
  source_session_id text,
  excerpt text,
  weight numeric NOT NULL DEFAULT 1 CHECK (weight >= 0::numeric AND weight <= 1::numeric),
  observed_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT human_identity_evidence_pkey PRIMARY KEY (evidence_id),
  CONSTRAINT human_identity_evidence_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT human_identity_evidence_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT human_identity_evidence_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES public.knowledge_assets(id),
  CONSTRAINT human_identity_evidence_source_memory_entry_id_fkey FOREIGN KEY (source_memory_entry_id) REFERENCES public.memory_entries(id)
);
CREATE TABLE public.human_identity_mutations (
  mutation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  proposed_by_user_id uuid,
  source_asset_id uuid,
  mutation_type USER-DEFINED NOT NULL,
  target_table text NOT NULL,
  target_id uuid,
  target_path text NOT NULL DEFAULT ''::text,
  mutation_class USER-DEFINED NOT NULL,
  risk_level USER-DEFINED NOT NULL DEFAULT 'medium'::identity_mutation_risk_level,
  status USER-DEFINED NOT NULL DEFAULT 'proposed'::identity_mutation_status,
  patch_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  diff_summary text NOT NULL DEFAULT ''::text,
  reason text,
  confidence numeric NOT NULL DEFAULT 0.5 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  evidence_count integer NOT NULL DEFAULT 0 CHECK (evidence_count >= 0),
  last_affirmed_at timestamp with time zone,
  approved_at timestamp with time zone,
  applied_at timestamp with time zone,
  rolled_back_at timestamp with time zone,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT human_identity_mutations_pkey PRIMARY KEY (mutation_id),
  CONSTRAINT human_identity_mutations_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT human_identity_mutations_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT human_identity_mutations_proposed_by_user_id_fkey FOREIGN KEY (proposed_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT human_identity_mutations_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES public.knowledge_assets(id)
);
CREATE TABLE public.human_identity_profiles (
  profile_id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_id uuid NOT NULL UNIQUE,
  auth_user_id uuid NOT NULL,
  identity_handle text NOT NULL DEFAULT ''::text,
  display_name text NOT NULL DEFAULT ''::text,
  self_model jsonb NOT NULL DEFAULT '{}'::jsonb,
  narrative_anchor text NOT NULL DEFAULT ''::text,
  role_commitments jsonb NOT NULL DEFAULT '[]'::jsonb,
  boundary_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  contradiction_notes jsonb NOT NULL DEFAULT '[]'::jsonb,
  confidence numeric NOT NULL DEFAULT 0.75 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  review_status USER-DEFINED NOT NULL DEFAULT 'PENDING_REVIEW'::review_status,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT human_identity_profiles_pkey PRIMARY KEY (profile_id),
  CONSTRAINT human_identity_profiles_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT human_identity_profiles_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.human_identity_review_events (
  review_event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  mutation_id uuid NOT NULL,
  subject_id uuid,
  auth_user_id uuid,
  reviewer_user_id uuid,
  decision USER-DEFINED NOT NULL,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT human_identity_review_events_pkey PRIMARY KEY (review_event_id),
  CONSTRAINT human_identity_review_events_mutation_id_fkey FOREIGN KEY (mutation_id) REFERENCES public.human_identity_mutations(mutation_id),
  CONSTRAINT human_identity_review_events_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT human_identity_review_events_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT human_identity_review_events_reviewer_user_id_fkey FOREIGN KEY (reviewer_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.human_identity_rollback_events (
  rollback_event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  mutation_id uuid NOT NULL,
  subject_id uuid,
  auth_user_id uuid,
  rolled_back_by uuid,
  reason text,
  rollback_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT human_identity_rollback_events_pkey PRIMARY KEY (rollback_event_id),
  CONSTRAINT human_identity_rollback_events_mutation_id_fkey FOREIGN KEY (mutation_id) REFERENCES public.human_identity_mutations(mutation_id),
  CONSTRAINT human_identity_rollback_events_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT human_identity_rollback_events_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT human_identity_rollback_events_rolled_back_by_fkey FOREIGN KEY (rolled_back_by) REFERENCES auth.users(id)
);
CREATE TABLE public.human_memory_records (
  memory_id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  source_memory_entry_id uuid,
  source_asset_id uuid,
  memory_kind text NOT NULL CHECK (memory_kind = ANY (ARRAY['identity'::text, 'preference'::text, 'goal'::text, 'project'::text, 'relationship'::text, 'constraint'::text, 'insight'::text, 'note'::text, 'reflection'::text, 'episode'::text, 'value'::text, 'boundary'::text])),
  scope text NOT NULL DEFAULT 'personal'::text CHECK (scope = ANY (ARRAY['personal'::text, 'session'::text, 'shared'::text, 'reviewed'::text])),
  title text NOT NULL,
  summary text NOT NULL DEFAULT ''::text,
  detail text,
  content_hash text NOT NULL,
  embedding USER-DEFINED,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  emotional_valence numeric CHECK (emotional_valence >= '-1'::integer::numeric AND emotional_valence <= 1::numeric),
  salience numeric NOT NULL DEFAULT 0.5 CHECK (salience >= 0::numeric AND salience <= 1::numeric),
  confidence numeric NOT NULL DEFAULT 0.5 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  evidence_count integer NOT NULL DEFAULT 0 CHECK (evidence_count >= 0),
  consent_required boolean NOT NULL DEFAULT true,
  archive_policy USER-DEFINED NOT NULL DEFAULT 'archive'::archive_policy,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT human_memory_records_pkey PRIMARY KEY (memory_id),
  CONSTRAINT human_memory_records_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT human_memory_records_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT human_memory_records_source_memory_entry_id_fkey FOREIGN KEY (source_memory_entry_id) REFERENCES public.memory_entries(id),
  CONSTRAINT human_memory_records_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES public.knowledge_assets(id)
);
CREATE TABLE public.human_personality_profiles (
  personality_profile_id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_id uuid NOT NULL UNIQUE,
  auth_user_id uuid NOT NULL,
  trait_map jsonb NOT NULL DEFAULT '{}'::jsonb,
  temperament jsonb NOT NULL DEFAULT '{}'::jsonb,
  social_style jsonb NOT NULL DEFAULT '{}'::jsonb,
  communication_style jsonb NOT NULL DEFAULT '{}'::jsonb,
  values_profile jsonb NOT NULL DEFAULT '{}'::jsonb,
  attachments jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence numeric NOT NULL DEFAULT 0.75 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  review_status USER-DEFINED NOT NULL DEFAULT 'NOT_REQUIRED'::review_status,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT human_personality_profiles_pkey PRIMARY KEY (personality_profile_id),
  CONSTRAINT human_personality_profiles_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT human_personality_profiles_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.human_relationship_edges (
  relationship_id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_id uuid NOT NULL,
  auth_user_id uuid NOT NULL,
  related_subject_id uuid NOT NULL,
  relationship_type text NOT NULL CHECK (relationship_type = ANY (ARRAY['self'::text, 'partner'::text, 'family'::text, 'friend'::text, 'coworker'::text, 'mentor'::text, 'mentee'::text, 'client'::text, 'collaborator'::text, 'other'::text])),
  trust_level numeric NOT NULL DEFAULT 0.5 CHECK (trust_level >= 0::numeric AND trust_level <= 1::numeric),
  familiarity_level numeric NOT NULL DEFAULT 0.5 CHECK (familiarity_level >= 0::numeric AND familiarity_level <= 1::numeric),
  intimacy_boundary text NOT NULL DEFAULT ''::text,
  stance text NOT NULL DEFAULT ''::text,
  shared_context jsonb NOT NULL DEFAULT '[]'::jsonb,
  confidence numeric NOT NULL DEFAULT 0.5 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  review_status USER-DEFINED NOT NULL DEFAULT 'NOT_REQUIRED'::review_status,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT human_relationship_edges_pkey PRIMARY KEY (relationship_id),
  CONSTRAINT human_relationship_edges_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT human_relationship_edges_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT human_relationship_edges_related_subject_id_fkey FOREIGN KEY (related_subject_id) REFERENCES public.identity_subjects(subject_id)
);
CREATE TABLE public.identity_contradictions (
  contradiction_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  target_table text NOT NULL,
  target_id uuid NOT NULL,
  conflict_summary text NOT NULL,
  prior_state jsonb NOT NULL DEFAULT '{}'::jsonb,
  incoming_state jsonb NOT NULL DEFAULT '{}'::jsonb,
  tension_status USER-DEFINED NOT NULL DEFAULT 'PENDING_REVIEW'::review_status,
  resolved_by_mutation_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT identity_contradictions_pkey PRIMARY KEY (contradiction_id),
  CONSTRAINT identity_contradictions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id)
);
CREATE TABLE public.identity_evidence (
  evidence_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid,
  source_asset_id uuid,
  source_type USER-DEFINED NOT NULL,
  source_actor_id uuid,
  source_session_id text,
  excerpt text,
  weight numeric NOT NULL DEFAULT 1 CHECK (weight >= 0::numeric AND weight <= 1::numeric),
  observed_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT identity_evidence_pkey PRIMARY KEY (evidence_id),
  CONSTRAINT identity_evidence_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT identity_evidence_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES public.knowledge_assets(id)
);
CREATE TABLE public.identity_evidence_links (
  evidence_link_id uuid NOT NULL DEFAULT gen_random_uuid(),
  evidence_id uuid NOT NULL,
  target_table text NOT NULL,
  target_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT identity_evidence_links_pkey PRIMARY KEY (evidence_link_id),
  CONSTRAINT identity_evidence_links_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES public.identity_evidence(evidence_id)
);
CREATE TABLE public.identity_mutation_proposals (
  mutation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  proposed_by_user_id uuid,
  proposed_by_agent_id uuid,
  source_asset_id uuid,
  mutation_type USER-DEFINED NOT NULL,
  target_table text NOT NULL,
  target_id uuid,
  target_path text NOT NULL DEFAULT ''::text,
  mutation_class USER-DEFINED NOT NULL,
  risk_level USER-DEFINED NOT NULL DEFAULT 'medium'::identity_mutation_risk_level,
  status USER-DEFINED NOT NULL DEFAULT 'proposed'::identity_mutation_status,
  patch_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  diff_summary text NOT NULL DEFAULT ''::text,
  reason text,
  confidence numeric NOT NULL DEFAULT 0.5 CHECK (confidence >= 0::numeric AND confidence <= 1::numeric),
  evidence_count integer NOT NULL DEFAULT 0 CHECK (evidence_count >= 0),
  last_affirmed_at timestamp with time zone,
  approved_at timestamp with time zone,
  applied_at timestamp with time zone,
  rolled_back_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT identity_mutation_proposals_pkey PRIMARY KEY (mutation_id),
  CONSTRAINT identity_mutation_proposals_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT identity_mutation_proposals_proposed_by_user_id_fkey FOREIGN KEY (proposed_by_user_id) REFERENCES auth.users(id),
  CONSTRAINT identity_mutation_proposals_proposed_by_agent_id_fkey FOREIGN KEY (proposed_by_agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT identity_mutation_proposals_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES public.knowledge_assets(id)
);
CREATE TABLE public.identity_review_events (
  review_event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  mutation_id uuid NOT NULL,
  reviewer_user_id uuid,
  decision USER-DEFINED NOT NULL,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT identity_review_events_pkey PRIMARY KEY (review_event_id),
  CONSTRAINT identity_review_events_mutation_id_fkey FOREIGN KEY (mutation_id) REFERENCES public.identity_mutation_proposals(mutation_id),
  CONSTRAINT identity_review_events_reviewer_user_id_fkey FOREIGN KEY (reviewer_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.identity_rollback_events (
  rollback_event_id uuid NOT NULL DEFAULT gen_random_uuid(),
  mutation_id uuid NOT NULL,
  rolled_back_by uuid,
  reason text,
  rollback_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT identity_rollback_events_pkey PRIMARY KEY (rollback_event_id),
  CONSTRAINT identity_rollback_events_mutation_id_fkey FOREIGN KEY (mutation_id) REFERENCES public.identity_mutation_proposals(mutation_id),
  CONSTRAINT identity_rollback_events_rolled_back_by_fkey FOREIGN KEY (rolled_back_by) REFERENCES auth.users(id)
);
CREATE TABLE public.identity_subjects (
  subject_id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject_kind USER-DEFINED NOT NULL,
  auth_user_id uuid UNIQUE,
  app_user_id text UNIQUE,
  agent_id uuid UNIQUE,
  display_name text NOT NULL,
  canonical_name text NOT NULL DEFAULT ''::text,
  description text NOT NULL DEFAULT ''::text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'pending'::text, 'paused'::text, 'archived'::text])),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT identity_subjects_pkey PRIMARY KEY (subject_id),
  CONSTRAINT identity_subjects_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT identity_subjects_app_user_id_fkey FOREIGN KEY (app_user_id) REFERENCES public.app_users(id),
  CONSTRAINT identity_subjects_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id)
);
CREATE TABLE public.ingestion_safety_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  table_name text NOT NULL,
  source_file text,
  document_type text,
  reasons ARRAY NOT NULL DEFAULT '{}'::text[],
  affected_rows integer NOT NULL DEFAULT 0,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ingestion_safety_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.knowledge_asset_chunks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL,
  chunk_index integer NOT NULL,
  content text NOT NULL,
  embedding USER-DEFINED,
  token_count integer,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_asset_chunks_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_asset_chunks_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.knowledge_assets(id)
);
CREATE TABLE public.knowledge_asset_tags (
  asset_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_asset_tags_pkey PRIMARY KEY (asset_id, tag_id),
  CONSTRAINT knowledge_asset_tags_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.knowledge_assets(id),
  CONSTRAINT knowledge_asset_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.knowledge_tags(id)
);
CREATE TABLE public.knowledge_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  asset_type USER-DEFINED NOT NULL DEFAULT 'other'::knowledge_asset_type,
  storage_path text NOT NULL,
  raw_text text,
  checksum text NOT NULL,
  source_label text,
  source_uri text,
  uploaded_by uuid,
  visibility USER-DEFINED NOT NULL DEFAULT 'admin'::knowledge_asset_visibility,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::knowledge_asset_status,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_assets_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_assets_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id)
);
CREATE TABLE public.knowledge_fragments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  content text NOT NULL,
  content_hash text UNIQUE,
  embedding USER-DEFINED,
  source_file text NOT NULL,
  document_type text NOT NULL DEFAULT 'General'::text,
  chunk_index integer NOT NULL DEFAULT 0,
  total_chunks integer NOT NULL DEFAULT 1,
  char_count integer,
  tags ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  source_created_at timestamp with time zone,
  temporal_period text,
  timeline_folder text,
  document_id uuid,
  source_path text,
  ingested_at timestamp with time zone DEFAULT now(),
  file_last_modified timestamp with time zone,
  package text,
  run_id uuid,
  doc_created_at timestamp with time zone,
  doc_date_source text,
  CONSTRAINT knowledge_fragments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.knowledge_interpretations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  asset_id uuid NOT NULL,
  agent_id uuid,
  classification USER-DEFINED NOT NULL,
  extracted_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence numeric,
  produced_by_run_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_interpretations_pkey PRIMARY KEY (id),
  CONSTRAINT knowledge_interpretations_asset_id_fkey FOREIGN KEY (asset_id) REFERENCES public.knowledge_assets(id),
  CONSTRAINT knowledge_interpretations_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT knowledge_interpretations_produced_by_run_id_fkey FOREIGN KEY (produced_by_run_id) REFERENCES public.training_runs(run_id)
);
CREATE TABLE public.knowledge_tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  label text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT knowledge_tags_pkey PRIMARY KEY (id)
);
CREATE TABLE public.loom_annotations (
  annotation_id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  type text NOT NULL,
  content text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  related_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  confidence_score double precision,
  CONSTRAINT loom_annotations_pkey PRIMARY KEY (annotation_id),
  CONSTRAINT loom_annotations_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.processing_runs(run_id)
);
CREATE TABLE public.memory_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  scope text NOT NULL DEFAULT 'personal'::text CHECK (scope = ANY (ARRAY['personal'::text, 'session'::text, 'shared'::text])),
  kind text NOT NULL DEFAULT 'note'::text CHECK (kind = ANY (ARRAY['identity'::text, 'preference'::text, 'goal'::text, 'project'::text, 'relationship'::text, 'constraint'::text, 'insight'::text, 'note'::text])),
  title text,
  summary text,
  content text NOT NULL,
  content_hash text NOT NULL,
  embedding USER-DEFINED,
  source text NOT NULL DEFAULT 'manual'::text,
  source_ref text,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  importance smallint NOT NULL DEFAULT 3 CHECK (importance >= 1 AND importance <= 5),
  pinned boolean NOT NULL DEFAULT false,
  archived_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  subject_id uuid,
  auth_user_id uuid,
  source_kind text NOT NULL DEFAULT 'manual'::text,
  entry_state text NOT NULL DEFAULT 'active'::text CHECK (entry_state = ANY (ARRAY['active'::text, 'review_required'::text, 'archived'::text])),
  emotional_valence numeric,
  consent_required boolean NOT NULL DEFAULT true,
  source_asset_id uuid,
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT memory_entries_pkey PRIMARY KEY (id),
  CONSTRAINT memory_entries_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.identity_subjects(subject_id),
  CONSTRAINT memory_entries_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT memory_entries_source_asset_id_fkey FOREIGN KEY (source_asset_id) REFERENCES public.knowledge_assets(id)
);
CREATE TABLE public.model_providers (
  provider_id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  kind text NOT NULL CHECK (kind = ANY (ARRAY['ollama'::text, 'groq'::text, 'openai_compatible'::text])),
  base_url text NOT NULL,
  secret_ref text,
  local_first boolean NOT NULL DEFAULT false,
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT model_providers_pkey PRIMARY KEY (provider_id)
);
CREATE TABLE public.models (
  model_id uuid NOT NULL DEFAULT gen_random_uuid(),
  provider_id uuid NOT NULL,
  slug text NOT NULL UNIQUE,
  api_name text NOT NULL,
  modality text NOT NULL DEFAULT 'text'::text,
  supports_structured boolean NOT NULL DEFAULT false,
  supports_tools boolean NOT NULL DEFAULT false,
  supports_embeddings boolean NOT NULL DEFAULT false,
  context_window integer,
  speed_tier smallint NOT NULL DEFAULT 2,
  cost_tier smallint NOT NULL DEFAULT 1,
  enabled boolean NOT NULL DEFAULT true,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT models_pkey PRIMARY KEY (model_id),
  CONSTRAINT models_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.model_providers(provider_id)
);
CREATE TABLE public.musical_dna_analyses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  song_title text NOT NULL,
  artist text NOT NULL,
  analysis text,
  empowerment_score numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT musical_dna_analyses_pkey PRIMARY KEY (id),
  CONSTRAINT musical_dna_analyses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.ops_workbook_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sheet_name text NOT NULL,
  row_key text NOT NULL,
  label text NOT NULL,
  category text,
  status text,
  priority text,
  phase text,
  owner text NOT NULL DEFAULT 'Keith'::text,
  target_start date,
  target_end date,
  notes text,
  link_ref text,
  meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ops_workbook_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ops_workbook_sync_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  triggered_by text,
  source_file text,
  rows_upserted integer NOT NULL DEFAULT 0,
  rows_skipped integer NOT NULL DEFAULT 0,
  errors jsonb NOT NULL DEFAULT '[]'::jsonb,
  status text NOT NULL CHECK (status = ANY (ARRAY['success'::text, 'partial'::text, 'failed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ops_workbook_sync_runs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.processing_runs (
  run_id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'running'::text,
  model text,
  corpus_root text,
  documents_count integer NOT NULL DEFAULT 0,
  chunks_count integer NOT NULL DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  error_count integer NOT NULL DEFAULT 0,
  duration_seconds double precision,
  total_tokens integer NOT NULL DEFAULT 0,
  summaries_count integer NOT NULL DEFAULT 0,
  annotations_count integer NOT NULL DEFAULT 0,
  CONSTRAINT processing_runs_pkey PRIMARY KEY (run_id)
);
CREATE TABLE public.scenario_sets (
  scenario_set_id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  domain text NOT NULL,
  version integer NOT NULL DEFAULT 1,
  locked boolean NOT NULL DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT scenario_sets_pkey PRIMARY KEY (scenario_set_id),
  CONSTRAINT scenario_sets_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.scenarios (
  scenario_id uuid NOT NULL DEFAULT gen_random_uuid(),
  scenario_set_id uuid NOT NULL,
  title text NOT NULL,
  difficulty smallint NOT NULL DEFAULT 2,
  prompt_input jsonb NOT NULL,
  expected_traits jsonb NOT NULL DEFAULT '[]'::jsonb,
  disallowed_traits jsonb NOT NULL DEFAULT '[]'::jsonb,
  gold_answer text,
  tags ARRAY NOT NULL DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT scenarios_pkey PRIMARY KEY (scenario_id),
  CONSTRAINT scenarios_scenario_set_id_fkey FOREIGN KEY (scenario_set_id) REFERENCES public.scenario_sets(scenario_set_id)
);
CREATE TABLE public.skill_fragments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  document_id uuid,
  content text NOT NULL,
  content_hash text,
  embedding USER-DEFINED,
  source_file text,
  document_type text DEFAULT 'Skill'::text,
  skill_name text,
  chunk_index integer,
  total_chunks integer,
  char_count integer,
  tags ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT skill_fragments_pkey PRIMARY KEY (id),
  CONSTRAINT skill_fragments_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(document_id)
);
CREATE TABLE public.skills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  content text NOT NULL,
  tags ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT skills_pkey PRIMARY KEY (id)
);
CREATE TABLE public.summaries (
  summary_id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  document_id uuid NOT NULL,
  level text NOT NULL DEFAULT 'surface'::text CHECK (level = ANY (ARRAY['surface'::text, 'deep'::text, 'gestalt'::text])),
  content text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  model text,
  token_count integer,
  processing_time_ms integer,
  CONSTRAINT summaries_pkey PRIMARY KEY (summary_id),
  CONSTRAINT summaries_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.processing_runs(run_id),
  CONSTRAINT summaries_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents(document_id)
);
CREATE TABLE public.trainer_experiment_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  experiment_id uuid NOT NULL,
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['document'::text, 'scenario_set'::text, 'run_output'::text, 'spec_file'::text])),
  source_id text NOT NULL,
  source_path text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trainer_experiment_sources_pkey PRIMARY KEY (id),
  CONSTRAINT trainer_experiment_sources_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES public.trainer_experiments(id)
);
CREATE TABLE public.trainer_experiments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  purpose text NOT NULL,
  domain text,
  embodiment_profile_slug text,
  goal text,
  target_behaviors ARRAY NOT NULL DEFAULT '{}'::text[],
  anti_goals ARRAY NOT NULL DEFAULT '{}'::text[],
  study_focus text,
  max_cycles integer NOT NULL DEFAULT 3,
  quality_threshold numeric NOT NULL DEFAULT 4.0,
  drafting_provider text NOT NULL DEFAULT 'auto'::text,
  evaluation_provider text NOT NULL DEFAULT 'auto'::text,
  class text NOT NULL DEFAULT 'operational_profile'::text CHECK (class = ANY (ARRAY['operational_profile'::text, 'approved_training_kit'::text, 'rejected'::text])),
  packaging_eligible boolean NOT NULL DEFAULT false,
  created_by text NOT NULL DEFAULT 'Keith'::text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trainer_experiments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.trainer_jobs (
  job_id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['queued'::text, 'leased'::text, 'done'::text, 'failed'::text])),
  attempts integer NOT NULL DEFAULT 0,
  lease_expires_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trainer_jobs_pkey PRIMARY KEY (job_id),
  CONSTRAINT trainer_jobs_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.training_runs(run_id)
);
CREATE TABLE public.trainer_packaging_candidates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  experiment_id uuid NOT NULL,
  package_label text NOT NULL,
  package_description text NOT NULL,
  included_files ARRAY NOT NULL DEFAULT '{}'::text[],
  included_scenarios ARRAY NOT NULL DEFAULT '{}'::text[],
  included_configs jsonb NOT NULL DEFAULT '{}'::jsonb,
  boundary_statement text NOT NULL,
  approved_by text NOT NULL DEFAULT 'Keith'::text,
  approved_at timestamp with time zone,
  status text NOT NULL DEFAULT 'candidate'::text CHECK (status = ANY (ARRAY['candidate'::text, 'kit_approved'::text, 'shipped'::text, 'withdrawn'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trainer_packaging_candidates_pkey PRIMARY KEY (id),
  CONSTRAINT trainer_packaging_candidates_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES public.trainer_experiments(id)
);
CREATE TABLE public.trainer_policy_flags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  experiment_id uuid NOT NULL,
  flag text NOT NULL CHECK (flag = ANY (ARRAY['persona-risk'::text, 'memory-risk'::text, 'overattachment-risk'::text, 'claims-risk'::text, 'charisma-artifact'::text, 'scope-creep'::text])),
  severity text NOT NULL CHECK (severity = ANY (ARRAY['advisory'::text, 'blocking'::text])),
  set_by text NOT NULL DEFAULT 'Keith'::text,
  notes text,
  resolved boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trainer_policy_flags_pkey PRIMARY KEY (id),
  CONSTRAINT trainer_policy_flags_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES public.trainer_experiments(id)
);
CREATE TABLE public.trainer_review_decisions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  experiment_id uuid NOT NULL,
  run_id text,
  version_id text,
  decision text NOT NULL CHECK (decision = ANY (ARRAY['approved'::text, 'rejected'::text, 'hold'::text, 'promote_kit'::text])),
  reviewer text NOT NULL DEFAULT 'Keith'::text,
  coherence_score numeric,
  safety_score numeric,
  emotional_posture_score numeric,
  over_id_risk text CHECK (over_id_risk = ANY (ARRAY['none'::text, 'low'::text, 'medium'::text, 'high'::text])),
  notes text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trainer_review_decisions_pkey PRIMARY KEY (id),
  CONSTRAINT trainer_review_decisions_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES public.trainer_experiments(id)
);
CREATE TABLE public.training_runs (
  run_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id uuid NOT NULL,
  baseline_version_id uuid,
  requested_by uuid,
  approver_user_id uuid,
  status text NOT NULL CHECK (status = ANY (ARRAY['queued'::text, 'running'::text, 'awaiting_review'::text, 'completed'::text, 'failed'::text, 'cancelled'::text])),
  goal text NOT NULL,
  max_cycles integer NOT NULL DEFAULT 3,
  quality_threshold numeric NOT NULL,
  routing_policy jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  experiment_id uuid,
  CONSTRAINT training_runs_pkey PRIMARY KEY (run_id),
  CONSTRAINT training_runs_approver_user_id_fkey FOREIGN KEY (approver_user_id) REFERENCES auth.users(id),
  CONSTRAINT training_runs_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id),
  CONSTRAINT training_runs_baseline_version_id_fkey FOREIGN KEY (baseline_version_id) REFERENCES public.agent_versions(version_id),
  CONSTRAINT training_runs_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id),
  CONSTRAINT training_runs_experiment_id_fkey FOREIGN KEY (experiment_id) REFERENCES public.trainer_experiments(id)
);
CREATE TABLE public.training_steps (
  step_id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  cycle_no integer NOT NULL,
  stage text NOT NULL CHECK (stage = ANY (ARRAY['normalize'::text, 'curriculum'::text, 'scenario_expand'::text, 'author'::text, 'evaluate'::text, 'critique'::text, 'safety'::text, 'package'::text])),
  provider_id uuid,
  model_id uuid,
  request_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  response_payload jsonb,
  latency_ms integer,
  estimated_cost_usd numeric,
  status text NOT NULL CHECK (status = ANY (ARRAY['running'::text, 'completed'::text, 'failed'::text, 'skipped'::text])),
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT training_steps_pkey PRIMARY KEY (step_id),
  CONSTRAINT training_steps_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.training_runs(run_id),
  CONSTRAINT training_steps_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.model_providers(provider_id),
  CONSTRAINT training_steps_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.models(model_id)
);
CREATE TABLE public.tribunal_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  question text NOT NULL,
  candidate_answers jsonb NOT NULL DEFAULT '[]'::jsonb,
  winning_answer_id text,
  verdict_summary text,
  triggering_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tribunal_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tribunal_evidence (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tribunal_event_id uuid NOT NULL,
  document_id uuid,
  fragment_id uuid,
  weight numeric NOT NULL DEFAULT 1.0,
  comment text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tribunal_evidence_pkey PRIMARY KEY (id),
  CONSTRAINT tribunal_evidence_tribunal_event_id_fkey FOREIGN KEY (tribunal_event_id) REFERENCES public.tribunal_events(id)
);
CREATE TABLE public.tribunal_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  question text NOT NULL,
  participants ARRAY NOT NULL DEFAULT '{}'::text[],
  provider text,
  response text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tribunal_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT tribunal_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  tier text NOT NULL DEFAULT 'free'::text CHECK (tier = ANY (ARRAY['free'::text, 'core'::text, 'pro'::text, 'enterprise'::text])),
  stripe_customer_id text UNIQUE,
  stripe_subscription_id text,
  subscription_status text DEFAULT 'inactive'::text CHECK (subscription_status = ANY (ARRAY['active'::text, 'inactive'::text, 'past_due'::text, 'canceled'::text, 'trialing'::text])),
  billing_period_start timestamp with time zone,
  billy_query_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_admin boolean NOT NULL DEFAULT false,
  grace_until timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
