import { describe, expect, it } from "vitest";

import { exportArtifact, inferContentFormat } from "../../shared/gen-engine/index.js";
import type { GeneratedArtifact } from "../../shared/gen-engine/types.js";

function makeArtifact(overrides: Partial<GeneratedArtifact> = {}): GeneratedArtifact {
  return {
    id: "artifact-1",
    title: "Alias Artifact",
    type: "code",
    content: "print('hello world')",
    contentFormat: "code",
    sourceCaptureIds: [],
    sourceArtifactIds: [],
    destination: "download-only",
    createdAt: "2026-06-25T00:00:00.000Z",
    metadata: {},
    ...overrides,
  };
}

describe("gen-engine format aliases", () => {
  it("infers the python, mindmap, diagram, and graph content formats", () => {
    expect(inferContentFormat("code", "text/x-python")).toBe("python");
    expect(inferContentFormat("mind-map")).toBe("mindmap");
    expect(inferContentFormat("diagram", "text/vnd.mermaid")).toBe("mermaid");
    expect(inferContentFormat("mermaid")).toBe("mermaid");
    expect(inferContentFormat("graph", "application/vnd.gestaltview.graph+json")).toBe("graph");
    expect(inferContentFormat("workflow")).toBe("graph");
  });

  it("exports python artifacts with a .py filename and python mime type", () => {
    const artifact = makeArtifact({
      title: "Python Helper",
      contentFormat: "python",
      content: "print('hello world')",
    });

    const exported = exportArtifact(artifact, "python");

    expect(exported.fileName).toBe("python_helper.py");
    expect(exported.mimeType).toBe("text/x-python;charset=utf-8");
    expect(exported.content).toBe("print('hello world')");
  });

  it("passes through HTML mindmap exports without double wrapping", () => {
    const artifact = makeArtifact({
      title: "Mind Map",
      contentFormat: "mindmap",
      content: "<!doctype html><html><body><h1>Mind Map</h1></body></html>",
    });

    const exported = exportArtifact(artifact, "mindmap");

    expect(exported.fileName).toBe("mind_map.html");
    expect(exported.mimeType).toBe("text/html;charset=utf-8");
    expect(exported.content).toContain("<h1>Mind Map</h1>");
    expect(exported.content).not.toContain("Generated by GestaltView");
  });

  it("exports mermaid diagram artifacts as plain mermaid source", () => {
    const artifact = makeArtifact({
      title: "System Flow",
      contentFormat: "mermaid",
      content: "graph TD\nA-->B",
    });

    const exported = exportArtifact(artifact, "mermaid");

    expect(exported.fileName).toBe("system_flow.mmd");
    expect(exported.mimeType).toBe("text/vnd.mermaid;charset=utf-8");
    expect(exported.content).toBe("graph TD\nA-->B");
  });
});
