#!/usr/bin/env node
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROFILES_DIR = path.resolve(__dirname, "../embodiment_profiles");
const OUTPUT_FILE = path.resolve(__dirname, "../shared/embodiment/generated.ts");

function slugify(filename: string): string {
  return filename
    .replace(/\.embodiment\.json$/, "")
    .replace(/\.json$/, "");
}

function isProfileFile(filename: string): boolean {
  return filename.endsWith(".embodiment.json") && !filename.startsWith("_");
}

function sortObjectKeys(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(sortObjectKeys);
  }

  if (!value || typeof value !== "object") {
    return value;
  }

  return Object.keys(value)
    .sort((left, right) => left.localeCompare(right))
    .reduce((accumulator, key) => {
      accumulator[key] = sortObjectKeys((value as Record<string, unknown>)[key]);
      return accumulator;
    }, {} as Record<string, unknown>);
}

function main() {
  const files = fs
    .readdirSync(PROFILES_DIR)
    .filter(isProfileFile)
    .sort((left, right) => left.localeCompare(right));

  const profiles: Record<string, unknown> = {};

  for (const file of files) {
    const raw = fs.readFileSync(path.join(PROFILES_DIR, file), "utf-8");

    try {
      const parsed = JSON.parse(raw);
      const slug = typeof parsed.slug === "string" && parsed.slug.trim() ? parsed.slug.trim() : slugify(file);
      profiles[slug] = parsed;
      console.log(`  ✓ ${slug}`);
    } catch (error) {
      console.error(`  ✗ Failed to parse ${file}:`, error);
      process.exit(1);
    }
  }

  const sortedProfiles = sortObjectKeys(profiles);
  const output = `// AUTO-GENERATED by scripts/generate-embodiment-registry.ts
// Do not hand-edit. Run: npx tsx scripts/generate-embodiment-registry.ts
import type { EmbodimentProfile } from "./types.js";

export const EMBODIMENT_PROFILES: Record<string, EmbodimentProfile> = ${JSON.stringify(sortedProfiles, null, 2)} as const;
`;

  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`\n✓ Generated ${Object.keys(profiles).length} profiles → shared/embodiment/generated.ts`);
}

main();
