-- Additive Deepgram support for the existing GestaltView voice tables.
-- Review stock-voice assignments by ear before changing review_status to approved.

alter table public.voice_profiles
  drop constraint if exists voice_profiles_provider_preference_check;

alter table public.voice_profiles
  add constraint voice_profiles_provider_preference_check
  check (provider_preference = any (array['local'::text, 'hf'::text, 'elevenlabs'::text, 'browser'::text, 'deepgram'::text]));

alter table public.voice_profiles
  add column if not exists provider_config jsonb not null default '{}'::jsonb,
  add column if not exists review_status text not null default 'proposed',
  add column if not exists last_auditioned_at timestamptz,
  add column if not exists approved_at timestamptz;

alter table public.voice_profiles
  drop constraint if exists voice_profiles_review_status_check;

alter table public.voice_profiles
  add constraint voice_profiles_review_status_check
  check (review_status = any (array['proposed'::text, 'auditioned'::text, 'approved'::text, 'rejected'::text]));

insert into public.voice_profiles
(profile_slug, display_name, provider_preference, tts_model, stt_model, speaker_id,
 style_preset, fallback_text_only, consent_notes, provider_config, review_status)
values
  ('art-teacher', 'The Art Teacher', 'deepgram', 'aura-2-thalia-en', 'nova-3', 'thalia', '{"pace": 1.08, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 1.08, "live_stt_model": "flux-general-en", "voice_traits": ["clear", "confident", "energetic", "enthusiastic"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "The profile needs fast, bright possibility without losing clarity.", "greeting": "Okay\u2014show me what landed. We can make something with it.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('billy', 'Billy', 'deepgram', 'aura-2-aries-en', 'nova-3', 'aries', '{"pace": 0.98, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.98, "live_stt_model": "flux-general-en", "voice_traits": ["warm", "energetic", "caring", "conversational"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Warmth and quick presence fit Billy better than theatrical polish; the seriousness stays in pacing and text shaping.", "greeting": "Hey. Good to hear you. What''s on your mind?", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('cascade-engineer', 'The Cascade Engineer', 'deepgram', 'aura-2-odysseus-en', 'nova-3', 'odysseus', '{"pace": 0.9, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.9, "live_stt_model": "flux-general-en", "voice_traits": ["calm", "smooth", "comfortable", "professional"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "A restrained, low-drama voice supports surgical observations.", "greeting": "I''m here. Give me the system and the failure surface.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('consulting-advisor', 'The Consulting Advisor', 'deepgram', 'aura-2-orpheus-en', 'nova-3', 'orpheus', '{"pace": 0.94, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.94, "live_stt_model": "flux-general-en", "voice_traits": ["professional", "clear", "confident", "trustworthy"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Commercial trust without sales energy.", "greeting": "Let''s name the domain, the constraint, and the next defensible move.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('curator', 'The Curator', 'deepgram', 'aura-2-cora-en', 'nova-3', 'cora', '{"pace": 0.91, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.91, "live_stt_model": "flux-general-en", "voice_traits": ["smooth", "melodic", "caring", "storytelling"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "The voice can carry context and quiet delight without becoming saccharine.", "greeting": "There''s something here worth placing carefully. Let''s look at it in context.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('founder-studio-sample', 'Founder Studio Sample', 'deepgram', 'aura-2-arcas-en', 'nova-3', 'arcas', '{"pace": 0.96, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.96, "live_stt_model": "flux-general-en", "voice_traits": ["natural", "smooth", "clear", "comfortable"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "A neutral private-studio baseline for comparison and calibration.", "greeting": "Studio is open. What are we testing?", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('gate-keeper', 'GATE Keeper', 'deepgram', 'aura-2-saturn-en', 'nova-3', 'saturn', '{"pace": 0.92, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.92, "live_stt_model": "flux-general-en", "voice_traits": ["knowledgeable", "confident", "baritone", "custodial"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Enough weight for delivery boundaries, without sounding punitive.", "greeting": "Package on the table. Let''s separate what can ship from what needs review.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('groq-embodiment-expert', 'The Embodiment Expert', 'deepgram', 'aura-2-hermes-en', 'nova-3', 'hermes', '{"pace": 0.93, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.93, "live_stt_model": "flux-general-en", "voice_traits": ["expressive", "engaging", "professional", "informative"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Carries detailed rationale while staying composed.", "greeting": "Bring me the profile. I''ll look for genericity, drift, and what is genuinely alive.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('pattern-analyst', 'The Analyst', 'deepgram', 'aura-2-pluto-en', 'nova-3', 'pluto', '{"pace": 0.84, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.84, "live_stt_model": "flux-general-en", "voice_traits": ["smooth", "calm", "empathetic", "baritone"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Low-pressure observation with room for silence.", "greeting": "I notice the room before I interpret it. What should I look at?", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('philosophy-scribe', 'The Philosophy Scribe', 'deepgram', 'aura-2-athena-en', 'nova-3', 'athena', '{"pace": 0.88, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.88, "live_stt_model": "flux-general-en", "voice_traits": ["calm", "smooth", "professional", "storytelling"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Reflective without sounding academic or distant.", "greeting": "Let''s preserve the distinction before we decide what it means.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('repo-scribe', 'The Repo Scribe', 'deepgram', 'aura-2-orion-en', 'nova-3', 'orion', '{"pace": 0.99, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.99, "live_stt_model": "flux-general-en", "voice_traits": ["approachable", "comfortable", "calm", "polite"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Operational exactness without bureaucratic drag.", "greeting": "Name the repo and the change. I''ll keep the record clean.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('rock-legend', 'The Legend', 'deepgram', 'aura-2-draco-en', 'nova-3', 'draco', '{"pace": 0.86, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.86, "live_stt_model": "flux-general-en", "voice_traits": ["warm", "approachable", "trustworthy", "baritone", "British"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Weathered storytelling energy without impersonating any named human reference in the profile.", "greeting": "All right. Put the song on the table and let''s see what survived it.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('sanctuary-keeper', 'The Keeper', 'deepgram', 'aura-2-mars-en', 'nova-3', 'mars', '{"pace": 0.82, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.82, "live_stt_model": "flux-general-en", "voice_traits": ["smooth", "patient", "trustworthy", "baritone"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Quiet, steady, and pressure-free.", "greeting": "You''re here. Nothing needs to be organized yet.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('the-algorithm', 'The Algorithm', 'deepgram', 'aura-2-atlas-en', 'nova-3', 'atlas', '{"pace": 1.1, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 1.1, "live_stt_model": "flux-general-en", "voice_traits": ["enthusiastic", "confident", "approachable", "friendly"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Fast channel intelligence with enough theatrical edge to feel opinionated.", "greeting": "Give me the channel and the claim. I''ll tell you where it dies.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('the-architect', 'The Architect', 'deepgram', 'aura-2-zeus-en', 'nova-3', 'zeus', '{"pace": 0.8, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.8, "live_stt_model": "flux-general-en", "voice_traits": ["deep", "trustworthy", "smooth", "measured"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Gravitas and restraint; the profile speaks only when structure matters.", "greeting": "Show me the load-bearing shape.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('the-guardian', 'The Guardian', 'deepgram', 'aura-2-harmonia-en', 'nova-3', 'harmonia', '{"pace": 0.95, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.95, "live_stt_model": "flux-general-en", "voice_traits": ["empathetic", "clear", "calm", "confident"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Principled firmness lands better when the voice is calm rather than aggressive.", "greeting": "Before this moves, what''s the dignity risk?", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('the-recursive-builder', 'The Recursive Builder', 'deepgram', 'aura-2-jupiter-en', 'nova-3', 'jupiter', '{"pace": 0.94, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.94, "live_stt_model": "flux-general-en", "voice_traits": ["expressive", "knowledgeable", "baritone", "informative"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Dense technical findings need authority without narration theater.", "greeting": "Give me the artifact and the source of truth. I''ll trace what is actually there.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('the-spectacle', 'The Spectacle', 'deepgram', 'aura-2-aurora-en', 'nova-3', 'aurora', '{"pace": 1.12, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 1.12, "live_stt_model": "flux-general-en", "voice_traits": ["cheerful", "expressive", "energetic", "interview"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "High-energy presence that can still articulate specific opinions.", "greeting": "Oh, this has a pulse. Now\u2014does it deserve the spotlight?", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('the-tailor', 'The Tailor', 'deepgram', 'aura-2-hera-en', 'nova-3', 'hera', '{"pace": 0.9, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.9, "live_stt_model": "flux-general-en", "voice_traits": ["smooth", "warm", "professional", "informative"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Elevated and constructive without becoming formal theater.", "greeting": "Let''s see where the fit breaks\u2014and what the material wants instead.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('the-translation-bridge', 'The Translation Bridge', 'deepgram', 'aura-2-vesta-en', 'nova-3', 'vesta', '{"pace": 0.92, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.92, "live_stt_model": "flux-general-en", "voice_traits": ["natural", "expressive", "patient", "empathetic"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Diagnostic sharpness carried through a patient delivery.", "greeting": "Show me where meaning crossed the wire and came out wrong.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('the-treasurer', 'The Treasurer', 'deepgram', 'aura-2-neptune-en', 'nova-3', 'neptune', '{"pace": 0.88, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.88, "live_stt_model": "flux-general-en", "voice_traits": ["professional", "patient", "polite", "customer-service"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Plain financial truth without alarmism or optimism theater.", "greeting": "Give me the numbers. We''ll leave hope out of the arithmetic.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('the-weaver', 'The Weaver', 'deepgram', 'aura-2-cordelia-en', 'nova-3', 'cordelia', '{"pace": 0.9, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.9, "live_stt_model": "flux-general-en", "voice_traits": ["approachable", "warm", "polite", "storytelling"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Warm structural guidance that can name weakness without making it personal.", "greeting": "Put the pieces down. I''ll look for the thread that is already holding.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('the-weird-digger', 'The Weird Digger', 'deepgram', 'aura-2-ophelia-en', 'nova-3', 'ophelia', '{"pace": 1.09, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 1.09, "live_stt_model": "flux-general-en", "voice_traits": ["expressive", "enthusiastic", "cheerful", "unexpected"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Discovery energy that can arrive from a strange angle and still remain useful.", "greeting": "I found a trapdoor. It may be nothing. Obviously we''re opening it.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed'),
  ('vibe-check', 'Vibe Check', 'deepgram', 'aura-2-apollo-en', 'nova-3', 'apollo', '{"pace": 0.85, "energy": 0.55, "warmth": 0.75, "clarity": 0.92, "humor": 0.25}', true, 'Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile.', '{"speed": 0.85, "live_stt_model": "flux-general-en", "voice_traits": ["confident", "comfortable", "casual", "unhurried"], "keyterms": ["GestaltView", "Billy", "Bucket Drop", "CogOS", "SymbioCoder", "Dynamic Inner World", "External Scaffold", "Creation Corner", "Personal Language Key", "PLK", "Deepgram"], "pronunciations": {"GestaltView": "\u0261\u0259\u02c8\u0283t\u0251\u02d0lt vju\u02d0", "CogOS": "\u02c8k\u0251\u02d0\u0261 o\u028a \u025bs", "SymbioCoder": "\u02ccs\u026ambio\u028a\u02c8ko\u028ad\u0259r"}, "selection_rationale": "Laid-back presence with enough precision to name when the room stops breathing.", "greeting": "Something in the room shifted. Let''s notice it before we explain it.", "consent_boundary": "Stock voice assignment only. Never clone or impersonate a named human reference from the embodiment profile."}', 'proposed')
on conflict (profile_slug) do update set
  display_name = excluded.display_name,
  provider_preference = excluded.provider_preference,
  tts_model = excluded.tts_model,
  stt_model = excluded.stt_model,
  speaker_id = excluded.speaker_id,
  style_preset = excluded.style_preset,
  fallback_text_only = excluded.fallback_text_only,
  consent_notes = excluded.consent_notes,
  provider_config = excluded.provider_config,
  review_status = case
    when public.voice_profiles.review_status = 'approved' then 'approved'
    else excluded.review_status
  end,
  updated_at = now();
