-- This migration originally hardened public.claim_trainer_job before
-- 20260330120000_trainer_core.sql created public.trainer_jobs. Keep this
-- historical version as an intentional no-op so a clean migration replay can
-- reach the core migration. The hardening is applied by the later
-- defer_trainer_security_hardening_until_core_exists migration.
