-- This post-state repair originally ran before its required human-profile
-- tables were created by 20260616000100_identity_subject_human_profiles.sql.
-- Keep the historical version as an intentional no-op. The complete,
-- idempotent repair now runs in 20260728030522_deferred_human_continuity_repair.sql.
